export interface TranslationSet {
  appName: string;
  appSubName: string;
  alertFeed: string;
  homeTab: string;
  reportTab: string;
  marketTab: string;
  groupsTab: string;
  profileTab: string;
  anonymous: string;
  postAnonymously: string;
  anonymousHint: string;
  phoneLogin: string;
  notVerified: string;
  activeUser: string;
  changeStatus: string;
  upvoteBtn: string;
  commentsTitle: string;
  addComment: string;
  marketGoods: string;
  marketServices: string;
  marketJobs: string;
  addListing: string;
  jobWage: string;
  contact: string;
  anonymousPlaceholder: string;
  villageSelection: string;
  resolvedSms: string;
  
  // Extra Inline Text conversions
  noComments: string;
  writeOpinion: string;
  notifFirst: string;
  reportLoginRequired: string;
  directForums: string;
  villageGroups: string;
  emptyGroup: string;
  anonymousMode: string;
  typeGroupMessage: string;
  groupLoginRequired: string;
  otpCredentials: string;
  sandboxHeader: string;
  sandboxDesc: string;
  villagerDesc: string;
  pradhanDesc: string;
  newAccount: string;
  nameLabel: string;
  phoneLabel: string;
  roleLabel: string;
  residentRole: string;
  pradhanRole: string;
  otpSend: string;
  otpCodeMsg: string;
  verifyCode: string;
  cancel: string;
  activeCredentials: string;
  actionReport: string;
  statusSelect: string;
  notesLabel: string;
  notesPlaceholder: string;
  webhookDesc: string;
  saveChanges: string;
  allCategories: string;
  contactSms: string;
  loginToContact: string;
  farmersGroup: string;
  youthGroup: string;
  womenGroup: string;
  generalGroup: string;
}

export const LANGUAGES_SUPPORTED = [
  { code: 'hi', nativeName: 'हिन्दी' },
  { code: 'en', nativeName: 'English' },
  { code: 'bn', nativeName: 'বাংলা' },
  { code: 'te', nativeName: 'తెలుగు' },
  { code: 'mr', nativeName: 'मराठी' },
  { code: 'ta', nativeName: 'தமிழ்' },
  { code: 'ur', nativeName: 'اردو' },
  { code: 'gu', nativeName: 'ગુજરાતી' },
  { code: 'kn', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', nativeName: 'മലയാളം' },
  { code: 'or', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'pa', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'as', nativeName: 'অসমীয়া' },
  { code: 'sa', nativeName: 'संस्कृतम्' },
  { code: 'bho', nativeName: 'भोजपुरी' },
  { code: 'mai', nativeName: 'मैथिली' },
  { code: 'es', nativeName: 'Español' },
  { code: 'fr', nativeName: 'Français' },
  { code: 'ar', nativeName: 'العربية' },
  { code: 'zh', nativeName: '中文' }
];

export const DICTIONARY: Record<string, TranslationSet> = {
  hi: {
    appName: "ग्रामस्वराज",
    appSubName: "ग्रामीण विकास एवं मंडी",
    alertFeed: "आपातकालीन चेतावनी",
    homeTab: "मुख्य फीड",
    reportTab: "शिकायत लिखें",
    marketTab: "मंडी बाजार",
    groupsTab: "ग्राम समूह",
    profileTab: "प्रोफाइल",
    anonymous: "गुप्त (अनाम)",
    postAnonymously: "अनाम रूप से पोस्ट करें",
    anonymousHint: "आपका नाम सार्वजनिक फीड और आम ग्रामीणों से पूरी तरह छुपाया जाएगा।",
    phoneLogin: "ओटीपी से लॉगिन",
    notVerified: "अपुष्ट खाता (पेंडिंग)",
    activeUser: "सक्रिय प्रोफाइल",
    changeStatus: "स्थिति बदलें",
    upvoteBtn: "मुझे भी यह समस्या है",
    commentsTitle: "चर्चा",
    addComment: "टिप्पणी लिखें",
    marketGoods: "अनाज / सामान",
    marketServices: "कृषि सेवा",
    marketJobs: "मजदूरी / नौकरी",
    addListing: "नया विज्ञापन जोड़ें",
    jobWage: "कीमत / वेतन",
    contact: "संपर्क हेतु लॉगिन",
    anonymousPlaceholder: "अनाम ग्रामीण",
    villageSelection: "सक्रिय गांव",
    resolvedSms: "रिपोर्टर को SMS भेजा",
    noComments: "कोई चर्चा नहीं हुई।",
    writeOpinion: "अपनी राय लिखें...",
    notifFirst: "टिप्पणी लिखने के लिए प्रोफाइल में ओटीपी से लॉगिन करें।",
    reportLoginRequired: "शिकायत दर्ज करने के लिए प्रोफाइल पर लॉगिन करें।",
    directForums: "विशेष ग्राम चौपाल",
    villageGroups: "ग्राम सभा समूह चर्चा",
    emptyGroup: "इस समूह में कोई चर्चा नहीं हुई है। पहले टिप्पणी लिखें!",
    anonymousMode: "अनाम मोड",
    typeGroupMessage: "चौपाल पर संदेश लिखें...",
    groupLoginRequired: "संदेह और चर्चा में शामिल होने के लिए फोन लॉगिन अनिवार्य है।",
    otpCredentials: "सुरक्षित पंजीकरण गेटवे",
    sandboxHeader: "त्वरित परीक्षण टूल्स",
    sandboxDesc: "विभिन्न भूमिकाओं के बीच बदलाव कर सुरक्षा नियमों और एसएमएस का लाइव टेस्ट करें:",
    villagerDesc: "शिकायत कर सकते हैं, मंडी विज्ञापन और उपवोट",
    pradhanDesc: "शिकायतों की स्थिति बदल सकते हैं, आपात चेतावनी प्रेषित",
    newAccount: "नया खाता लॉगिन (OTP / Phone)",
    nameLabel: "पूरा नाम",
    phoneLabel: "१० अंकों का मोबाइल नंबर",
    roleLabel: "खाता की भूमिका",
    residentRole: "ग्रामीण सदस्य (Resident)",
    pradhanRole: "ग्राम प्रधान (Village Head)",
    otpSend: "ओटीपी प्राप्त करें",
    otpCodeMsg: "पुष्टि कोड भेजा गया! टेस्ट हेतु 1234 एंटर करें:",
    verifyCode: "सत्यापित करें",
    cancel: "रद्द",
    activeCredentials: "सक्रिय लॉगिन विवरण",
    actionReport: "कार्यवाही रिपोर्ट दर्ज करें",
    statusSelect: "अद्यतित स्थिति चुनें",
    notesLabel: "कार्यवाही विवरण नोट्स",
    notesPlaceholder: "उदा: ट्रांसफर का फ्यूज बदल दिया गया है... बिजली लाइन सुचारू",
    webhookDesc: "समाधान करते ही, मेक / जैपियर हुक रिपोर्टर ग्रामीण को तुरंत व्हाट्सएप एसएमएस प्रेषित करेगा।",
    saveChanges: "सुरक्षित करें",
    allCategories: "सभी श्रेणी",
    contactSms: "संपर्क करें / SMS",
    loginToContact: "संपर्क देखने के लिए लॉगिन करें",
    farmersGroup: "🌾 किसान मंच",
    youthGroup: "🤝 युवा क्लब",
    womenGroup: "👩 महिला स्वयंसहायता",
    generalGroup: "💬 सामान्य मंच"
  },
  en: {
    appName: "GramSwaraj Mobile",
    appSubName: "Village Civic & Mandi Hub",
    alertFeed: "Emergency Alerts",
    homeTab: "Feed",
    reportTab: "File Complaint",
    marketTab: "Mandi Board",
    groupsTab: "Sub-Groups",
    profileTab: "Profile",
    anonymous: "Anonymous",
    postAnonymously: "Post Anonymously",
    anonymousHint: "Your name will be hidden in the public feeds for standard villagers.",
    phoneLogin: "Verify with OTP",
    notVerified: "Unverified Account",
    activeUser: "Active Profile",
    changeStatus: "Change Status",
    upvoteBtn: "I Have This Too",
    commentsTitle: "Dialogue",
    addComment: "Post Comment",
    marketGoods: "Goods / Produce",
    marketServices: "Services",
    marketJobs: "Jobs / Labor",
    addListing: "Post Listing",
    jobWage: "Price/Wage",
    contact: "Contact Merchant",
    anonymousPlaceholder: "Anonymized Member",
    villageSelection: "Active Village",
    resolvedSms: "SMS Notification Sent",
    noComments: "No comments yet.",
    writeOpinion: "Type comment...",
    notifFirst: "Verification required to post. Login first.",
    reportLoginRequired: "Account verification is required to submit. Please log in first.",
    directForums: "Direct Special Forums",
    villageGroups: "Village Group Dialogue",
    emptyGroup: "Begin the dialogue in this secure space.",
    anonymousMode: "Anonymous mode",
    typeGroupMessage: "Type message to group...",
    groupLoginRequired: "OTP authentication is required to send messages.",
    otpCredentials: "OTP Credentials Gate",
    sandboxHeader: "Assessor Sandbox Switch Pane",
    sandboxDesc: "Instantly swap roles to verify restricted status modifications or alerts workflows:",
    villagerDesc: "Can submit and upvote complaints, post classified ads",
    pradhanDesc: "Status triage, dispatch alerts & emergency broadcasts",
    newAccount: "Interactive Phone/OTP Verification",
    nameLabel: "Full Name",
    phoneLabel: "10-Digit Mobile",
    roleLabel: "Desired Account Role",
    residentRole: "Resident",
    pradhanRole: "Gram Pradhan",
    otpSend: "Send Verification OTP",
    otpCodeMsg: "Verification code sent. Enter mock OTP: 1234",
    verifyCode: "Verify Code",
    cancel: "Cancel",
    activeCredentials: "ACTIVE CREDENTIAL KEY",
    actionReport: "Complaint Dispatch Matrix",
    statusSelect: "Resolution Stage",
    notesLabel: "Dispatcher Dispatch Note",
    notesPlaceholder: "e.g., Transformer fuse safely replaced. Power lines isolated.",
    webhookDesc: "Choosing \"Resolved\" acts as a Zapier trigger webhook to dispatch automated WhatsApp confirmation SMS to reporter.",
    saveChanges: "Dispatch Action Update",
    allCategories: "All Categories",
    contactSms: "Contact / SMS",
    loginToContact: "Login to view contact",
    farmersGroup: "🌾 Farmers",
    youthGroup: "🤝 Youth Club",
    womenGroup: "👩 Women SHG",
    generalGroup: "💬 General Forum"
  },
  bn: {
    appName: "গ্রামস্বরাজ মোবাইল",
    appSubName: "গ্রামীণ ফোরাম ও মান্ডি",
    alertFeed: "জরুরী সতর্কতা",
    homeTab: "প্রধান ফিড",
    reportTab: "অভিযোগ দায়ের",
    marketTab: "মান্ডি বোর্ড",
    groupsTab: "গ্রামের গ্রুপ",
    profileTab: "প্রোফাইল",
    anonymous: "বেনামী",
    postAnonymously: "বেনামে পোস্ট করুন",
    anonymousHint: "আপনার নাম পাবলিক ফিড এবং সাধারণ গ্রামবাসীদের স্ক্রীন থেকে লুকানো হবে।",
    phoneLogin: "ওটিপি লগইন",
    notVerified: "অসমাপ্ত যাচাইকরণ",
    activeUser: "সক্রিয় প্রোফাইল",
    changeStatus: "অবস্থা পরিবর্তন",
    upvoteBtn: "আমারও এই সমস্যা আছে",
    commentsTitle: "আলোচনা",
    addComment: "মন্তব্য যোগ করুন",
    marketGoods: "পণ্য / শস্য",
    marketServices: "কৃষি সেবা",
    marketJobs: "দৈনিক মজুরি",
    addListing: "বিজ্ঞাপন যোগ করুন",
    jobWage: "মূল্য বা মজুরি",
    contact: "যোগাযোগ করতে লগইন",
    anonymousPlaceholder: "বেনামী গ্রামবাসী",
    villageSelection: "সক্রিয় গ্রাম",
    resolvedSms: "অভিযোগকারীকে SMS পাঠানো হয়েছে",
    noComments: "কোন আলোচনা হয়নি এখনো।",
    writeOpinion: "আপনার মতামত লিখুন...",
    notifFirst: "মন্তব্য পোস্ট করতে অনুগ্রহ করে ওটিপি লগইন করুন।",
    reportLoginRequired: "অভিযোগ জানাতে ওটিপি লগইন সম্পন্ন করা আবশ্যক।",
    directForums: "বিশেষ গ্রাম পঞ্চায়েত সভা",
    villageGroups: "গ্রাম সভা গ্রুপ আলোচনা",
    emptyGroup: "এই গ্রুপে এখনো কোনো চ্যাট হয়নি। প্রথম লিখুন!",
    anonymousMode: "নাম গোপন করুন",
    typeGroupMessage: "গ্রুপে বার্তা পাঠান...",
    groupLoginRequired: "গ্রুপ চ্যাটে কথা বলতে ওটিপি দিয়ে ফোন যাচাই করুন।",
    otpCredentials: "সুরক্ষিত ওটিপি গেটওয়ে",
    sandboxHeader: "স্যান্ডবক্স টেস্ট করুন",
    sandboxDesc: "ভূমিকা পরিবর্তন করে প্রধাণ বা সাধারণ গ্রামীণের নিরাপত্তা পরীক্ষা করুন:",
    villagerDesc: "অভিযোগ করতে ও মান্ডিতে পণ্য পোস্ট করতে পারবেন",
    pradhanDesc: "অভিযোগের সমাধান করতে ও পঞ্চায়েত জরুরি এলার্ট জারি করতে পারেন",
    newAccount: "নতুন অ্যাকাউন্ট লগইন (ওটিপি)",
    nameLabel: "পূর্ণ নাম",
    phoneLabel: "১০ সংখ্যার মোবাইল",
    roleLabel: "পছন্দের ভূমিকা",
    residentRole: "সাধারণ গ্রামবাসী",
    pradhanRole: "গ্রামের প্রধান (প্রধান)",
    otpSend: "ওটিপি পাঠান",
    otpCodeMsg: "ওটিপি কোড পাঠানো হয়েছে। পরীক্ষার জন্য 1234 লিখুন:",
    verifyCode: "কোড যাচাই করুন",
    cancel: "বাতিল করুন",
    activeCredentials: "সক্রিয় আইডি কার্ড",
    actionReport: "অভিযোগ সমাধান ম্যাট্রিক্স",
    statusSelect: "সমাধানের ধাপ নির্ধারণ",
    notesLabel: "সমাধানের বিবরণ বিবরণ",
    notesPlaceholder: "যেমন: ট্রান্সফরমার ফিউজ নতুন লাগানো হয়েছে। বিদ্যুৎ স্বাভাবিক।",
    webhookDesc: "সমাধান করলে, জেপিয়ার এবং মেক সার্ভিস স্বয়ংক্রিয়ভাবে গ্রামবাসীকে একটি এলার্ট পাঠাবে।",
    saveChanges: "পরিবর্তন সংরক্ষণ করুন",
    allCategories: "সব বিভাগ",
    contactSms: "যোগাযোগ / SMS",
    loginToContact: "নম্বর দেখতে লগইন করুন",
    farmersGroup: "🌾 কৃষক দল",
    youthGroup: "🤝 যুব সংঘ",
    womenGroup: "👩 মহিলা স্বনির্ভর গোষ্ঠী",
    generalGroup: "💬 সাধারণ সভা"
  },
  te: {
    appName: "గ్రామ స్వరాజ్",
    appSubName: "గ్రామ సేవలు & మండి బోర్డు",
    alertFeed: "అత్యవసర హెచ్చరికలు",
    homeTab: "గ్రామ ఫీడ్",
    reportTab: "ఫిర్యాదు చేయండి",
    marketTab: "మండి మార్కెట్",
    groupsTab: "గ్రామ సంఘాలు",
    profileTab: "ప్రొఫైల్",
    anonymous: "అజ్ఞాత",
    postAnonymously: "అజ్ఞాతంగా పోస్ట్ చేయండి",
    anonymousHint: "మీ పేరు పబ్లిక్ ఫీడ్‌లో సామాన్య గ్రామస్తులకు కనిపించదు.",
    phoneLogin: "OTP వెరిఫికేషన్",
    notVerified: "సరిచూడని ఖాతా",
    activeUser: "సక్రియ ప్రొఫైల్",
    changeStatus: "స్టేటస్ మార్చండి",
    upvoteBtn: "నాకు ఈ సమస్య ఉంది",
    commentsTitle: "సమీక్షలు",
    addComment: "వ్యాఖ్యను జోడించు",
    marketGoods: "వ్యవసాయ ఉత్పత్తులు",
    marketServices: "వ్యవసాయ సేవలు",
    marketJobs: "కూలి పనులు",
    addListing: "కొత్త ప్రకటన జోడించు",
    jobWage: "ధర / వేతనం",
    contact: "సంప్రదించడానికి లాగిన్ అవ్వండి",
    anonymousPlaceholder: "అజ్ఞాత గ్రామస్థుడు",
    villageSelection: "ఎంచుకున్న గ్రామం",
    resolvedSms: "రిపోర్టర్‌కు SMS పంపబడింది",
    noComments: "ఇంకా ఎలాంటి కామెంట్లు లేవు.",
    writeOpinion: "మీ వ్యాఖ్య రాయండి...",
    notifFirst: "వ్యాఖ్య పోస్ట్ చేయడానికి దయచేసి OTP తో లాగిన్ చేయండి.",
    reportLoginRequired: "ఫిర్యాదు సమర్పించడానికి ఫోన్ ధృవీకరణ అవసరం.",
    directForums: "ప్రత్యేక గ్రామ సభ",
    villageGroups: "గ్రామ సంఘాల చర్చా వేదిక",
    emptyGroup: "ఈ గ్రూప్‌లో ఎలాంటి చర్చ జరగలేదు. మీరే ప్రారంభించండి!",
    anonymousMode: "అజ్ఞాత మోడ్",
    typeGroupMessage: "మీ సందేశాన్ని ఇక్కడ రాయండి...",
    groupLoginRequired: "గ్రూప్ మేసేజ్‌లు పంపడానికి ఫోన్ లాగిన్ తప్పనిసరి.",
    otpCredentials: "సురక్షిత లాగిన్ గేట్‌వే",
    sandboxHeader: "సాండ్‌బాక్స్ టెస్టింగ్ విభాగం",
    sandboxDesc: "గ్రామ ప్రధాన్, గ్రామస్థుల పాత్రలను మార్చి పనుల ప్రగతిని పరీక్షించండి:",
    villagerDesc: "ఫిర్యాదు చేయవచ్చు, ఓటు వేయవచ్చు, మండిలో ప్రకటనలు పెట్టవచ్చు",
    pradhanDesc: "ఫిర్యాదుల స్థితిని మార్చవచ్చు మరియు అత్యవసర హెచ్చరికలు జారీచేయవచ్చు",
    newAccount: "OTP తో లాగిన్ అవ్వండి",
    nameLabel: "పూర్తి పేరు",
    phoneLabel: "10 అంకెల మొబైల్ సంఖ్య",
    roleLabel: "ఖాతా రకం",
    residentRole: "గ్రామస్థుడు (Resident)",
    pradhanRole: "గ్రామ ప్రధాన్ (Village Head)",
    otpSend: "OTP పంపండి",
    otpCodeMsg: "ధృవీకరణ సంకేతం పంపబడింది. పరీక్ష కోసం 1234 ఉపయోగించండి:",
    verifyCode: "కోడ్ ధృవీకరించండి",
    cancel: "రద్దు",
    activeCredentials: "ప్రస్తుత వినియోగదారు వివరాలు",
    actionReport: "ఫిర్యాదు పరిష్కార చర్యలు",
    statusSelect: "పరిష్కార దశ",
    notesLabel: "పరిష్కార వివరాలు",
    notesPlaceholder: "ఉదా: ట్రాన్స్‌ఫార్మర్ పోల్ బాగుచేయబడింది. విద్యుత్ సరఫరా పునరుద్ధరించబడింది.",
    webhookDesc: "ఫిర్యాదు పరిష్కారం అయిన వెంటనే, గ్రామస్థునికి ఆటోమేటిక్‌గా వాట్సాప్ SMS వెళ్తుంది.",
    saveChanges: "వివరాలు సేవ్ చేయండి",
    allCategories: "అన్ని రకాలు",
    contactSms: "సంప్రదించండి",
    loginToContact: "చూడటానికి లాగిన్ అవ్వండి",
    farmersGroup: "🌾 రైతు సంఘం",
    youthGroup: "🤝 యువజన సంఘం",
    womenGroup: "👩 మహిళా సంఘాలు (SHG)",
    generalGroup: "💬 గ్రామ వేదిక"
  },
  mr: {
    appName: "ग्रामस्वराज",
    appSubName: "ग्रामीण विकास आणि मंडी मंच",
    alertFeed: "तातडीची सूचना",
    homeTab: "मुख्य चर्चा",
    reportTab: "तक्रार नोंदवा",
    marketTab: "मंडी बाजार",
    groupsTab: "ग्राम समूह",
    profileTab: "माहिती",
    anonymous: "गुप्त (अनामिक)",
    postAnonymously: "गोपनीय रित्या पाठवा",
    anonymousHint: "तुमचे नाव इतर सामान्य ग्रामस्थांच्या स्क्रीनपासून सुरक्षितपणे लपविले जाईल.",
    phoneLogin: "OTP ने लॉगिन करा",
    notVerified: "पडताळणी शिल्लक",
    activeUser: "सक्रिय प्रोफाईल",
    changeStatus: "स्थिती बदला",
    upvoteBtn: "मलाही ही अडचण आहे",
    commentsTitle: "चर्चा",
    addComment: "टीप जोडा",
    marketGoods: "मालाचा तपशील",
    marketServices: "शेती सेवा",
    marketJobs: "रोजगार / मजुरी",
    addListing: "नवीन जाहिरात",
    jobWage: "किंमत / रोजंदारी",
    contact: "संपर्क करण्यासाठी लॉगिन करा",
    anonymousPlaceholder: "अनामिक ग्रामस्थ",
    villageSelection: "सक्रिय गाव",
    resolvedSms: "तक्रारदाराला निश्चिती SMS पाठवला",
    noComments: "अजून कोणतीही चर्चा झालेली नाही.",
    writeOpinion: "तुमचे मत टाका...",
    notifFirst: "टिप्पणी लिहिण्यासाठी कृपया प्रोफाइलमध्ये ओटिपी लॉगिन करा.",
    reportLoginRequired: "तक्रार दाखल करण्यासाठी आधी मोबाईल पडताळणी पूर्ण करा.",
    directForums: "ग्राम चौपाल चर्चा",
    villageGroups: "ग्राम पंचायत समूह संवाद",
    emptyGroup: "या समूहात कोणीही संवाद सुरू केला नाही. तुम्ही सुरुवात करा!",
    anonymousMode: "अनामिक मोड",
    typeGroupMessage: "चौपाल संदेश लिहा...",
    groupLoginRequired: "कामाच्या चर्चेत सहभागी होण्यासाठी ओटिपी लॉगिन आवश्यक आहे.",
    otpCredentials: "सुरक्षित ओटिपी लॉगिन",
    sandboxHeader: "चाचणी मोड (Sandbox)",
    sandboxDesc: "ग्रामीण अथवा प्रधान भूमिका बदलून ऑटोमॅटिक एसएमएसची चाचणी करा:",
    villagerDesc: "तक्रारी नोंदवू शकतात, मंडी मधे शेती माल विकू शकतात",
    pradhanDesc: "तक्रारींचे निवारण दर्जा बदलू शकतात व संपूर्ण गावाला अलर्ट देऊ शकतात",
    newAccount: "मोबाईल नंबर व्हेरिफिकेशन",
    nameLabel: "पूर्ण नाव",
    phoneLabel: "१० अंकी मोबाईल",
    roleLabel: "निवडलेली भूमिका",
    residentRole: "ग्रामस्थ नागरिक",
    pradhanRole: "सरपंच / ग्राम प्रधान (Village Head)",
    otpSend: "ओटीपी पाठवा",
    otpCodeMsg: "व्हेरिफिकेशन कोड पाठवला आहे. टेस्टसाठी 1234 वापरा:",
    verifyCode: "कोड पडताळा",
    cancel: "रद्द करा",
    activeCredentials: "सध्याचे लॉगिन तपशील",
    actionReport: "तक्रार निवारण कृती",
    statusSelect: "निवारण स्थिती",
    notesLabel: "कृती अहवाल तपशील",
    notesPlaceholder: "उदा: रोहित्र बदलण्यात आले आहे. वीज पुरवठा सुरळीत पुन्हा सुरू.",
    webhookDesc: "निवारण होताच, नागरिकाला तात्काळ व्हॉट्सॲप / एसएमएस द्वारे त्वरित कळवले जाते.",
    saveChanges: "बदल जतन करा",
    allCategories: "सर्व प्रकार",
    contactSms: "संपर्क साधा / SMS",
    loginToContact: "संपर्क पाहण्यासाठी लॉगिन करा",
    farmersGroup: "🌾 शेतकरी बांधव",
    youthGroup: "🤝 युवा मंडळ",
    womenGroup: "👩 महिला बचत गट",
    generalGroup: "💬 विकास साधना"
  },
  ta: {
    appName: "கிராம ஸ்வராஜ்",
    appSubName: "கிராம அரங்கம் & மண்டி போர்டு",
    alertFeed: "அவசர அறிவிப்புகள்",
    homeTab: "முகப்பு",
    reportTab: "புகார் அளிக்கவும்",
    marketTab: "மண்டி சந்தை",
    groupsTab: "உள்ளூர் குழுக்கள்",
    profileTab: "சுயவிவரம்",
    anonymous: "அநாமதேயம்",
    postAnonymously: "பெயரின்றி பதிவிடு",
    anonymousHint: "பொது பதிவுகளில் உங்கள் பெயர் மற்ற கிராம மக்களுக்கு தெரியாது.",
    phoneLogin: "OTP சரிபார்ப்பு",
    notVerified: "சரிபார்க்கப்படாத கணக்கு",
    activeUser: "செயலில் உள்ள கணக்கு",
    changeStatus: "நிலையை மாற்று",
    upvoteBtn: "எனக்கும் இந்த பிரச்சினை உள்ளது",
    commentsTitle: "கருத்துகள்",
    addComment: "கருத்து சேர்க்க",
    marketGoods: "பொருட்கள் / விளைச்சல்",
    marketServices: "சேவைகள் / வாடகை",
    marketJobs: "தினக்கூலி வேலைகள்",
    addListing: "விளம்பரம் சேர்",
    jobWage: "விலை / கூலி",
    contact: "தொடர்பு கொள்ள லாகின் செய்க",
    anonymousPlaceholder: "பெயர் மறைத்த பயனர்",
    villageSelection: "தேர்ந்தெடுக்கப்பட்ட கிராமம்",
    resolvedSms: "SMS செய்தி அனுப்பப்பட்டது",
    noComments: "இன்னும் கருத்துக்கள் இல்லை.",
    writeOpinion: "உங்கள் கருத்தை எழுதுங்கள்...",
    notifFirst: "கருத்து பதிவிட சுயவிவரப் பக்கத்தில் மொபைல் லாகின் செய்யவும்.",
    reportLoginRequired: "புகார் அளிக்க மொபைல் எண் சரிபார்ப்பு அவசியமாகும்.",
    directForums: "கிராம பஞ்சாயத்து சபை",
    villageGroups: "கிராம சபை குழு உரையாடல்",
    emptyGroup: "இந்த குழுவில் இன்னும் உரையாடல் இல்லை. நீங்கள் துவங்குங்கள்!",
    anonymousMode: "அநாமதேய முறை",
    typeGroupMessage: "செய்தி தட்டச்சு செய்க...",
    groupLoginRequired: "குழு விவாதங்களில் பங்கேற்க OTP லாகின் தேவை.",
    otpCredentials: "பாதுகாப்பான OTP நுழைவாயில்",
    sandboxHeader: "டெஸ்டிங் சாண்ட்பாக்ஸ்",
    sandboxDesc: "பஞ்சாயத்து தலைவர் அல்லது கிராமவாசி நிலைகளை மாற்றி சோதிக்கவும்:",
    villagerDesc: "புகார் பதிவு செய்ய, ஆதரிக்க, மண்டி விளம்பரம் செய்ய முடியும்",
    pradhanDesc: "புகார்களை சரிசெய்ய மற்றும் அவசர அறிவிப்புகளை விநியோகிக்க முடியும்",
    newAccount: "OTP மூலம் உள்ளேறுங்கள்",
    nameLabel: "முழு பெயர்",
    phoneLabel: "10-இலக்க மொபைல் எண்",
    roleLabel: "விரும்பும் பொறுப்பு",
    residentRole: "கிராமவாசி (Resident)",
    pradhanRole: "கிராம தலைவர் (Gram Pradhan)",
    otpSend: "OTP அனுப்பு",
    otpCodeMsg: "சரிபார்ப்பு குறியீடு அனுப்பப்பட்டது. சோதனைக்கு 1234 பயன்படுத்தவும்:",
    verifyCode: "சரிபார்",
    cancel: "ரத்து செய்",
    activeCredentials: "தற்போதைய பயனர் விவரம்",
    actionReport: "புகார் தீர்வு மேலாண்மை",
    statusSelect: "தீர்வு நிலை",
    notesLabel: "டெஸ்பாட்ச் குறிப்பு",
    notesPlaceholder: "எ.கா: மின் மாற்றி மின் கம்பி சரி செய்யப்பட்டது. மின்சாரம் வழங்கப்பட்டது.",
    webhookDesc: "தீர்வு எட்டப்பட்டவுடன், கிராமவாசிருக்கு தானியங்கி வாட்ஸ்அப் SMS அனுப்பப்படும்.",
    saveChanges: "மாற்றங்களைச் சேமி",
    allCategories: "அனைத்து பிரிவுகள்",
    contactSms: "தொடர்பு கொள்ள",
    loginToContact: "பார்க்க லாகின் செய்யவும்",
    farmersGroup: "🌾 உழவர் தளம்",
    youthGroup: "🤝 இளைஞர் மன்றம்",
    womenGroup: "👩 மகளிர் குழு (SHG)",
    generalGroup: "💬 பொது அரங்கம்"
  },
  ur: {
    appName: "گرام سوراج موبائل",
    appSubName: "پنچایت کونسل اور منڈی بورڈ",
    alertFeed: "ہنگامی الرٹ",
    homeTab: "کھلا فیڈ",
    reportTab: "شکایت درج کریں",
    marketTab: "منڈی بازار",
    groupsTab: "لوکل گروپس",
    profileTab: "پروفائل",
    anonymous: "نامعلوم",
    postAnonymously: "بغیر نام کے پوسٹ کریں",
    anonymousHint: "آپ کا نام عام دیہاتیوں کی فیڈ پر اور اسکرینوں پر کبھی ظاہر نہیں ہوگا۔",
    phoneLogin: "او ٹی پی تصدیق",
    notVerified: "غیر تصدیق شدہ",
    activeUser: "فعال پروفائل",
    changeStatus: "اسٹیٹس بدلیں",
    upvoteBtn: "مجھے بھی یہ مسئلہ ہے",
    commentsTitle: "بحث و مباحثہ",
    addComment: "رائے لکھیں",
    marketGoods: "فصلیں اور اشیاء",
    marketServices: "مزدوری و خدمات",
    marketJobs: "روزمرہ نوکری",
    addListing: "اشتہار شامل کریں",
    jobWage: "قیمت یا اجرت",
    contact: "رابطہ کرنے کیلئے لاگ ان کریں",
    anonymousPlaceholder: "نامعلوم دیہاتی",
    villageSelection: "منتخب گاؤں",
    resolvedSms: "شکایت کنندہ کو میسج روانہ",
    noComments: "کوئی رائے نہیں ہے۔",
    writeOpinion: "رائے درج کریں...",
    notifFirst: "تبصرہ کرنے کیلئے پروفائل میں جاکر فون تصدیق کریں۔",
    reportLoginRequired: "شکایت درج کرنے کیلئے او ٹی پی کی تصدیق لازمی ہے۔",
    directForums: "پنچایت بیٹھک",
    villageGroups: "لوکل کمیونٹی چیٹ گروپس",
    emptyGroup: "اس گروپ میں کوئی گفتگو نہیں ہوئی۔ آپ پہلی بات لکھیں!",
    anonymousMode: "نام چھپائیں",
    typeGroupMessage: "گروپ میں پیغام لکھیں...",
    groupLoginRequired: "گروپ ڈسکشن کیلئے لاگ ان ہونا ضروری ہے۔",
    otpCredentials: "محفوظ او ٹی پی تصدیق",
    sandboxHeader: "ٹیسٹ موڈ (سلیٹ)",
    sandboxDesc: "مختلف رولز تبدیل کرکے ایس ایم ایس آرڈر اور سیکورٹی کی جانچ کریں:",
    villagerDesc: "شکایات لکھیں اور منڈی میں اپنی سروسز کا اشتہار دیں",
    pradhanDesc: "شکایات کا اسٹیٹس بدل سکتے ہیں اور ہنگامی الرٹس جاری کرسکتے ہیں",
    newAccount: "نیا اکاؤنٹ لاگ ان",
    nameLabel: "پورا نام",
    phoneLabel: "دس ہندسوں کا موبائل نمبر",
    roleLabel: "اکاؤنٹ کا کردار",
    residentRole: "دیہاتی شہری (Resident)",
    pradhanRole: "گرام پردھان (Village Head)",
    otpSend: "او ٹی پی حاصل کریں",
    otpCodeMsg: "تصدیقی کوڈ بھیج دیا گیا۔ ٹیسٹ کیلئے 1234 لکھیں:",
    verifyCode: "کوڈ تصدیق کریں",
    cancel: "منسوخ",
    activeCredentials: "موجودہ لاگ ان کی تفصیلات",
    actionReport: "شکایت حل رپورٹ",
    statusSelect: "حل کرنے کا مرحلہ",
    notesLabel: "سرکاری حل کے نوٹس",
    notesPlaceholder: "مثلاً: لائن مین کے ذریعے بجلی کی تاریں اونچی کردی گئی ہیں۔",
    webhookDesc: "شکایت حل ہوتے ہی دیہاتی کو فورا واٹس ایپ ایس ایم ایس مل جائے گا۔",
    saveChanges: "تبدیلیاں محفوظ کریں",
    allCategories: "تمام کیٹیگری",
    contactSms: "رابطہ کریں / ایس ایم ایس",
    loginToContact: "نمبر دیکھنے کیلئے لاگ ان کریں",
    farmersGroup: "🌾 کسان بیٹھک",
    youthGroup: "🤝 نوجوان کلب",
    womenGroup: "👩 خواتین سیلف ہیلپ",
    generalGroup: "💬 عام مسائل"
  },
  gu: {
    appName: "ગ્રામ સ્વરાજ",
    appSubName: "ગ્રામ પંચાયત અને મંડી બોર્ડ",
    alertFeed: "તાકીદની ચેતવણીઓ",
    homeTab: "મુખ્ય ફીડ",
    reportTab: "ફરિયાદ નોંધીએ",
    marketTab: "મંડી બજાર",
    groupsTab: "ગ્રામ પંચાયત ગ્રુપ",
    profileTab: "પ્રોફાઇલ",
    anonymous: "અનામી (ગુપ્ત)",
    postAnonymously: "અનામી રૂપે પોસ્ટ કરો",
    anonymousHint: "તમારું નામ જાહેર પ્લેટફોર્મ પર સામાન્ય ગ્રામજનોથી સંપૂર્ણ છુપાવવામાં આવશે.",
    phoneLogin: "OTP વડે લોગીન",
    notVerified: "અપડેટ બાકી",
    activeUser: "સક્રિય પ્રોફાઇલ",
    changeStatus: "સ્થિતિ બદલો",
    upvoteBtn: "મને પણ આ સમસ્યા છે",
    commentsTitle: "ચર્ચા",
    addComment: "ટિપ્પણી ઉમેરો",
    marketGoods: "અનાજ અને સામગ્રી",
    marketServices: "કૃષિ સેવાઓ",
    marketJobs: "રોજગારી અને મજૂરી",
    addListing: "નવી જાહેરાત",
    jobWage: "કિંમત / મજૂરી",
    contact: "સંપર્ક માટે લોગીન કરો",
    anonymousPlaceholder: "અનામી ગ્રામજન",
    villageSelection: "સક્રિય ગામ",
    resolvedSms: "અરજદારને SMS મોકલી દીધો",
    noComments: "હજુ સુધી કોઈ ચર્ચા થઈ નથી.",
    writeOpinion: "તમારો અભિપ્રાય લખો...",
    notifFirst: "કમેન્ટ લખવા માટે પ્રોફાઇલમાં જઈ ફોન લોગીન કરો.",
    reportLoginRequired: "ફરિયાદ નોંધાવવા માટે મોબાઇલ ઓટીપી વેરિફિકેશન પૂર્ણ કરો.",
    directForums: "ખાસ ગ્રામ ચોપાલ",
    villageGroups: "ગ્રામ સભા ગ્રુપ ચર્ચા",
    emptyGroup: "આ ગ્રુપમાં હજુ કોઈ સંદેશા નથી. શરૂઆત કરો!",
    anonymousMode: "અનામી મોડ",
    typeGroupMessage: "સંદેશ લખો...",
    groupLoginRequired: "ચર્ચામાં ભાગ લેવા માટે ફોન લોગીન જરૂરી છે.",
    otpCredentials: "સુરક્ષિત ઓટીપી ચેનલ",
    sandboxHeader: "ટેસ્ટિંગ પેનલ (Sandbox)",
    sandboxDesc: "સરપંચ અથવા ગ્રામીણ રોલ બદલીને ઓટોમેટેડ એસએમએસ ચેક કરો:",
    villagerDesc: "ફરિયાદ કરી શકે છે અને મંડી બજારમાં જાહેરાત મૂકી શકે છે",
    pradhanDesc: "ફરિયાદો ઉકેલી શકે છે અને ગામમાં રેડ ઇમરજન્સી એલર્ટ જાહેર કરી શકે",
    newAccount: "મોબાઇલ વેરિફિકેશન",
    nameLabel: "આખું નામ",
    phoneLabel: "૧૦ આંકડાનો મોબાઇલ નંબર",
    roleLabel: "ઇચ્છિત હોદ્દો",
    residentRole: "ગ્રામીણ સદસ્ય",
    pradhanRole: "ગ્રામ સરપંચ (Village Head)",
    otpSend: "ઓટીપી મેળવો",
    otpCodeMsg: "વેરિફિકેશન કોડ મોકલ્યો છે. વેરિફિકેશન માટે 1234 વાપરો:",
    verifyCode: "કોડ ચકાસો",
    cancel: "રદ કરો",
    activeCredentials: "હાલની લોગીન માહિતી",
    actionReport: "ફરિયાદ નિવારણ અહેવાલ",
    statusSelect: "ઉકેલનો તબક્કો",
    notesLabel: "કાર્યવાહી વિગતો",
    notesPlaceholder: "દા.ત., પાણીની પાઇપલાઇનનું લીકેજ બંધ કરી વ્યવસ્થિત સમારકામ પૂરું કર્યું.",
    webhookDesc: "ફરિયાદ ઉકેલાતા જ, વેબસાઇટ સિસ્ટમ ગ્રામીણને વોટ્સએપ એસએમએસ મોકલશે.",
    saveChanges: "બદલાવ સાચવો",
    allCategories: "બધી કેટેગરી",
    contactSms: "સંપર્ક કરો / SMS",
    loginToContact: "જોવા માટે લોગીન કરો",
    farmersGroup: "🌾 ખેડૂત મંચ",
    youthGroup: "🤝 યુવા મંડળ",
    womenGroup: "👩 મહિલા સખી મંડળ",
    generalGroup: "💬 જનરલ ચર્ચા"
  },
  kn: {
    appName: "ಗ್ರಾಮ ಸ್ವರಾಜ್",
    appSubName: "ಗ್ರಾಮೀಣ ವಿಕಾಸ ಮತ್ತು ಮಂಡಿ ಮಂಡಳಿ",
    alertFeed: "ತುರ್ತು ಎಚ್ಚರಿಕೆ",
    homeTab: "ಗ್ರಾಮ ಫೀಡ್",
    reportTab: "ದೂರು ನೋಂದಣಿ",
    marketTab: "ಮಂಡಿ ಮಾರುಕಟ್ಟೆ",
    groupsTab: "ಗ್ರಾಮ ಗುಂಪುಗಳು",
    profileTab: "ಪ್ರೊಫೈಲ್",
    anonymous: "ಅನಾಮಧೇಯ",
    postAnonymously: "ಹೆಸರಿಲ್ಲದೆ ಪೋಸ್ಟ್ ಮಾಡಿ",
    anonymousHint: "ನಿಮ್ಮ ಹೆಸರು ಸಾರ್ವಜನಿಕ ಫೀಡ್‌ನಲ್ಲಿ ಇತರ ನಿವಾಸಿಗಳಿಗೆ ಗೋಚರಿಸುವುದಿಲ್ಲ.",
    phoneLogin: "OTP ದೃಢೀಕರಣ",
    notVerified: "ಪರಿಶೀಲಿಸದ ಖಾತೆ",
    activeUser: "ಸಕ್ರಿಯ ಪ್ರೊಫೈಲ್",
    changeStatus: "ಸ್ಥಿತಿ ಬದಲಾಯಿಸಿ",
    upvoteBtn: "ನನಗೂ ಈ ಸಮಸ್ಯೆ ಇದೆ",
    commentsTitle: "ಚರ್ಚೆಗಳು",
    addComment: "ಕಾಮೆಂಟ್ ಸೇರಿಸಿ",
    marketGoods: "ಕೃಷಿ ಸರಕುಗಳು",
    marketServices: "ಸೇವೆಗಳು / ಬಾಡಿಗೆ",
    marketJobs: "ದಿನಗೂಲಿ ಕೆಲಸಗಳು",
    addListing: "ಹೊಸ ಜಾಹೀರಾತು",
    jobWage: "ಬೆಲೆ ಅಥವಾ ಕೂಲಿ",
    contact: "ಸಂಪರ್ಕಿಸಲು ಲಾಗಿನ್ ಮಾಡಿ",
    anonymousPlaceholder: "ಅನಾಮಧೇಯ ಗ್ರಾಮಸ್ಥ",
    villageSelection: "ಸಕ್ರಿಯ ಗ್ರಾಮ",
    resolvedSms: "ದೂರುದಾರರಿಗೆ SMS ಕಳುಹಿಸಲಾಗಿದೆ",
    noComments: "ಯಾವುದೇ ಚರ್ಚೆ ನಡೆದಿಲ್ಲ.",
    writeOpinion: "ನಿಮ್ಮ ಕಾಮೆಂಟ್ ಬರೆಯಿರಿ...",
    notifFirst: "ಕಾಮೆಂಟ್ ಮಾಡಲು ದಯವಿಟ್ಟು ಫೋನ್ ವೆರಿಫಿಕೇಶನ್ ಮಾಡಿ.",
    reportLoginRequired: "ದೂರು ಸಲ್ಲಿಸಲು ಫೋನ್ ದೃಢೀಕರಣ ಅತ್ಯಗತ್ಯ.",
    directForums: "ವಿಶೇಷ ಗ್ರಾಮ ಚೌಪಡಿ",
    villageGroups: "ಗ್ರಾಮ ಸಭೆಯ ಗುಂಪು ಚರ್ಚೆ",
    emptyGroup: "ಈ ಗುಂಪಿನಲ್ಲಿ ಚರ್ಚೆಗಳು ನಡೆದಿಲ್ಲ. ಮೊದಲು ಬರೆಯಿರಿ!",
    anonymousMode: "ಅನಾಮಧೇಯ ಮೋಡ್",
    typeGroupMessage: "ನಿಮ್ಮ ಸಂದೇಶ ಬರೆಯಿರಿ...",
    groupLoginRequired: "ಗುಂಪು ಸಂಭಾಷಣೆಯಲ್ಲಿ ಭಾಗವಹಿಸಲು ಮೊಬೈಲ್ ಲಾಗಿನ್ ಬೇಕು.",
    otpCredentials: "ಸುರಕ್ಷಿತ ಲಾಗಿನ್ ಗೇಟ್‌ವೇ",
    sandboxHeader: "ಟೆಸ್ಟಿಂಗ್ ಪ್ಯಾನಲ್ (Sandbox)",
    sandboxDesc: "ಗ್ರಾಮ ಪ್ರಧಾನ ಅಥವಾ ಗ್ರಾಮಸ್ಥರ ರೋಲ್ ಬದಲಾಯಿಸಿ ಪರಿಶೀಲಿಸಿ:",
    villagerDesc: "ದೂರು ನೀಡಬಹುದು, ವೋಟ್ ಮಾಡಬಹುದು, ಮಂಡಿಯಲ್ಲಿ ಮಾರಾಟ ಜಾಹೀರಾತು ಹಾಕಬಹುದು",
    pradhanDesc: "ದೂರುಗಳ ಸ್ಥಿತಿ ಬದಲಾಯಿಸಬಹುದು ಮತ್ತು ತುರ್ತು ಸಂದೇಶ ರವಾನಿಸಬಹುದು",
    newAccount: "OTP ಮೂಲಕ ಲಾಗಿನ್ ಆಗಿ",
    nameLabel: "ಪೂರ್ಣ ಹೆಸರು",
    phoneLabel: "10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    roleLabel: "ಖಾತೆಯ ಪ್ರಕಾರ",
    residentRole: "ಗ್ರಾಮಸ್ಥ (Resident)",
    pradhanRole: "ಗ್ರಾಮ ಪ್ರಧಾನ (Village Head)",
    otpSend: "OTP ಕಳುಹಿಸಿ",
    otpCodeMsg: "ದೃಢೀಕರಣ ಕೋಡ್ ಕಳುಹಿಸಲಾಗಿದೆ. ಟೆಸ್ಟ್ ಗಾಗಿ 1234 ಬಳಸಿ:",
    verifyCode: "ಕೋಡ್ ಪರಿಶೀಲಿಸಿ",
    cancel: "ರದ್ದುಮಾಡು",
    activeCredentials: "ಪ್ರಸ್ತುತ ಬಳಕೆದಾರರ ವಿವರ",
    actionReport: "ದೂರು ಪರಿಹಾರ ಪ್ರಕ್ರಿಯೆ",
    statusSelect: "ಪರಿಹಾರದ ಹಂತ",
    notesLabel: "ಅಧಿಕೃತ ಟಿಪ್ಪಣಿಗಳು",
    notesPlaceholder: "ಉದಾ: ಕುಡಿಯುವ ನೀರಿನ ಪೈಪ್ ಲೈನ್ ದುರಸ್ತಿ ಮಾಡಲಾಗಿದೆ. ನೀರು ಸರಬರಾಜು ಸುಗಮವಾಗಿದೆ.",
    webhookDesc: "ಸಮಸ್ಯೆ ಬಗೆಹರಿದ ತಕ್ಷಣ ದೂರುದಾರರಿಗೆ ವಾಟ್ಸಾಪ್ ಎಸ್ ಎಂಎಸ್ ಆಟೋಮ್ಯಾಟಿಕ್ ಆಗಿ ರವಾನೆಯಾಗುತ್ತದೆ.",
    saveChanges: "ಬದಲಾವಣೆ ಉಳಿಸಿ",
    allCategories: "ಎಲ್ಲ ವಿಭಾಗಗಳು",
    contactSms: "ಸಂಪರ್ಕಿಸಿ",
    loginToContact: "ನೋಡಲು ಲಾಗಿನ್ ಮಾಡಿ",
    farmersGroup: "🌾 ರೈತರ ವೇದಿಕೆ",
    youthGroup: "🤝 ಯುವಕರ ಸಂಘ",
    womenGroup: "👩 ಮಹಿಳಾ ಸ್ವ ಸಹಾಯ ಸಂಘ",
    generalGroup: "💬 ಸಾಮಾನ್ಯ ಚೌಪಡಿ"
  },
  ml: {
    appName: "ഗ്രാമ സ്വരാജ്",
    appSubName: "ഗ്രാമ വികസനവും മണ്ടി ബോർഡും",
    alertFeed: "അടിയന്തിര അറിയിപ്പ്",
    homeTab: "ഗ്രാമ ഫീഡ്",
    reportTab: "പരാതി നൽകുക",
    marketTab: "മണ്ടി മാർക്കറ്റ്",
    groupsTab: "പ്രാദേശിക ഗ്രൂപ്പുകൾ",
    profileTab: "പ്രൊഫൈൽ",
    anonymous: "അജ്ഞാതൻ",
    postAnonymously: "രഹസ്യമായി പോസ്റ്റ് ചെയ്യുക",
    anonymousHint: "പൊതുവായ ഫീഡിൽ നിങ്ങളുടെ പേര് സാധാരണ ഗ്രാമീണർക്ക് കാണാൻ കഴിയില്ല.",
    phoneLogin: "OTP വെരിഫിക്കേഷൻ",
    notVerified: "സ്ഥിരീകരിക്കാത്ത അക്കൗണ്ട്",
    activeUser: "സജീവ പ്രൊഫൈൽ",
    changeStatus: "സ്റ്റാറ്റസ് മാറ്റുക",
    upvoteBtn: "എനിക്കും ഈ പ്രശ്നമുണ്ട്",
    commentsTitle: "അഭിപ്രായങ്ങൾ",
    addComment: "വിലയിരുത്തൽ ചേർക്കുക",
    marketGoods: "കാർഷിക ഉൽപ്പന്നങ്ങൾ",
    marketServices: "സേവനങ്ങൾ / വാടകക്ക്",
    marketJobs: "ദൈനംദിന തൊഴിലുകൾ",
    addListing: "പരസ്യം ചേർക്കുക",
    jobWage: "വില അല്ലെങ്കിൽ വേതനം",
    contact: "ബന്ധപ്പെടാൻ ലോഗിൻ ചെയ്യുക",
    anonymousPlaceholder: "പേര് മറച്ച ഗ്രാമീണൻ",
    villageSelection: "തിരഞ്ഞെടുത്ത ഗ്രാമം",
    resolvedSms: "പരാതിക്കാരന് SMS അയച്ചു",
    noComments: "ചർച്ചകൾ ഒന്നും നടന്നിട്ടില്ല.",
    writeOpinion: "അഭിപ്രായം രേഖപ്പെടുത്തുക...",
    notifFirst: "അഭിപ്രായം രേഖപ്പെടുത്താൻ ദയവായി ലോഗിൻ ചെയ്യുക.",
    reportLoginRequired: "പരാതി രജിസ്റ്റർ ചെയ്യാൻ മൊബൈൽ വെരിഫിക്കേഷൻ നിർബന്ധമാണ്.",
    directForums: "പ്രത്യേക കുടുംബശ്രീ / കൗൺസിൽ",
    villageGroups: "ഗ്രാമ സഭ ഗ്രൂപ്പ് ചർച്ചകൾ",
    emptyGroup: "ഈ ഗ്രൂപ്പിൽ സന്ദേശങ്ങൾ ഒന്നുമില്ല. ആദ്യപടിയായി നിങ്ങൾ എഴുതൂ!",
    anonymousMode: "അജ്ഞാത രീതി",
    typeGroupMessage: "സന്ദേശം ഇവിടെ ടൈപ്പ് ചെയ്യുക...",
    groupLoginRequired: "ഗ്രൂപ്പ് ചർച്ചയിൽ പങ്കെടുക്കാൻ മൊബൈൽ ഒടിപി ലോഗിൻ വേണം.",
    otpCredentials: "സുരക്ഷിത ഒടിപി ലോഗിൻ",
    sandboxHeader: "ടെസ്റ്റിംഗ് വിൻഡോ (Sandbox)",
    sandboxDesc: "പ്രസിഡൻ്റ് അല്ലെങ്കിൽ നിവാസിയുടെ റോൾ മാറ്റി മെസ്സേജ് നോട്ടിഫിക്കേഷൻ പരിശോധിക്കുക:",
    villagerDesc: "പരാതി നൽകാനും പിന്തുണക്കാനും മണ്ടിയിൽ പരസ്യപ്പെടുത്താനും സാധിക്കും",
    pradhanDesc: "പരാതികളിൽ തീർപ്പുണ്ടാക്കാനും അടിയന്തിര മുന്നറിയിപ്പ് നൽകാനും സാധിക്കും",
    newAccount: "OTP വഴി ലോഗിൻ ചെയ്യാം",
    nameLabel: "മുഴുവൻ പേര്",
    phoneLabel: "10 അക്ക മൊബൈൽ നമ്പർ",
    roleLabel: "ആവശ്യമായ റോൾ",
    residentRole: "ഗ്രാമീണൻ (Resident)",
    pradhanRole: "ഗ്രാമ പ്രസിഡൻ്റ് (Village Head)",
    otpSend: "OTP അയക്കുക",
    otpCodeMsg: "സ്ഥിരീകരണ കോഡ് അയച്ചു. ടെസ്റ്റിനായി 1234 ഉപയോഗിക്കുക:",
    verifyCode: "കോഡ് ശരിയാണോ എന്ന് നോക്കുക",
    cancel: "റദ്ദാക്കുക",
    activeCredentials: "നിലവിലെ ലോഗിൻ വിവരങ്ങൾ",
    actionReport: "പരാതി പരിഹാര സെൽ",
    statusSelect: "പരിഹാര ഘട്ടം",
    notesLabel: "ഔദ്യോഗിക കുറിപ്പ്",
    notesPlaceholder: "ഉദാ: കുടിവെള്ള പൈപ്പ് ലൈൻ ചോർച്ച പരിഹരിച്ചു. വിതരണം സുഗമമാക്കി.",
    webhookDesc: "പരാതി പരിഹരിക്കുമ്പോൾ ഗ്രാമീണർക്ക് വാട്സാപ്പിൽ മെസ്സേജ് ഓട്ടോമാറ്റിക്കായി അയക്കും.",
    saveChanges: "മാറ്റങ്ങൾ സേവ് ചെയ്യുക",
    allCategories: "എല്ലാ വിഭാഗങ്ങളും",
    contactSms: "ബന്ധപ്പെടുക / SMS",
    loginToContact: "കാണാൻ ലോഗിൻ ചെയ്യുക",
    farmersGroup: "🌾 കർഷക കൂട്ടായ്മ",
    youthGroup: "🤝 യുവജന ക്ലബ്ബ്",
    womenGroup: "👩 വനിതാ സ്വയംസഹായ സംഘം",
    generalGroup: "💬 പൊതു സഭ"
  },
  or: {
    appName: "ਗ੍ਰਾਮ ਸਵਰਾਜ",
    appSubName: "ଗ୍ରାମ ପଞ୍ଚାୟତ ଓ ମଣ୍ଡି ବୋର୍ଡ",
    alertFeed: "ଜରୁରୀ ସୂଚନା",
    homeTab: "ଗ୍ରାମ ଫିଡ୍",
    reportTab: "ଅଭିଯୋଗ ଲେଖନ୍ତୁ",
    marketTab: "ମଣ୍ଡି ବଜାର",
    groupsTab: "ଗ୍ରାମ ସମୂହ",
    profileTab: "ପ୍ରୋଫାଇଲ୍",
    anonymous: "ଗୁପ୍ତ (ଅନାମ)",
    postAnonymously: "ଅନାମ ଭାବେ ପୋଷ୍ଟ କରନ୍ତୁ",
    anonymousHint: "ଆପଣଙ୍କ ନାମ ସାର୍ବଜନୀନ ଫିଡରେ ସାଧାରଣ ଗ୍ରାମବାସୀଙ୍କ ଠାରୁ ଗୁପ୍ତ ରହିବ।",
    phoneLogin: "OTP ଲଗଇନ୍",
    notVerified: "ଯାଞ୍ଚ ହୋଇନି",
    activeUser: "ସକ୍ରିୟ ପ୍ରୋଫାଇଲ୍",
    changeStatus: "ସ୍ଥିତି ବଦଳାନ୍ତୁ",
    upvoteBtn: "ମୋର ମଧ୍ୟ ଏହି ସମସ୍ୟା ଅଛି",
    commentsTitle: "ଆଲୋଚନା",
    addComment: "ମତାମତ ଦିଅନ୍ତୁ",
    marketGoods: "ଶସ୍ୟ ଓ ସାମଗ୍ରୀ",
    marketServices: "କୃଷି ସେବା",
    marketJobs: "ଦୈନିକ ମଜୁରୀ",
    addListing: "ନୂଆ ବିଜ୍ଞାପନ",
    jobWage: "ମୂଲ୍ୟ କିମ୍ବା ମଜୁରୀ",
    contact: "ଯୋଗାଯୋଗ ପାଇଁ ଲଗଇନ୍",
    anonymousPlaceholder: "ଅନାମ ଗ୍ରାମବାସୀ",
    villageSelection: "ସକ୍ରିୟ ଗ୍ରାମ",
    resolvedSms: "ଅଭିଯୋଗକାରୀଙ୍କୁ SMS ପଠାଗଲା",
    noComments: "ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ମତାମତ ମିଳିନାହିଁ।",
    writeOpinion: "ନିଜର ପ୍ରତିକ୍ରିୟା ଲେଖନ୍ତୁ...",
    notifFirst: "ପ୍ରତିକ୍ରିୟା ଦେବାକୁ ପ୍ରୋଫାଇଲ୍ ଯାଇ ମୋବାଇଲ୍ ଲଗଇନ୍ କରନ୍ତୁ।",
    reportLoginRequired: "ଅଭିଯୋଗ ଦାଖଲ କରିବାକୁ ଓଟିପି ଯାଞ୍ଚ ଜରୁରୀ।",
    directForums: "ଗ୍ରାମ ସଭା ଚଉପାଲ୍",
    villageGroups: "ଗ୍ରାମ ପଞ୍ଚାୟତ ଚର୍ଚ୍ଚା ସମୂହ",
    emptyGroup: "ଏହି ଗ୍ରୁପରେ କୌଣସି ଚାଟ୍ ହୋଇନାହିଁ। ପ୍ରଥମେ ଆପଣ ଲେଖନ୍ତୁ!",
    anonymousMode: "ନାମ ଗୁପ୍ତ ରଖନ୍ତୁ",
    typeGroupMessage: "ଗ୍ରୁପ୍ ପାଇଁ ବାର୍ତ୍ତା ଲେଖନ୍ତୁ...",
    groupLoginRequired: "ଚର୍ଚ୍ଚାରେ ଭାଗ ନେବାକୁ ଓଟିପି ଯାଞ୍ଚ କରିବା ଆବଶ୍ୟକ।",
    otpCredentials: "ସୁରକ୍ଷିତ OTP ଲଗଇନ୍ ଗେଟୱେ",
    sandboxHeader: "ଟେଷ୍ଟିଂ ସ୍ୟାଣ୍ଡବକ୍ସ",
    sandboxDesc: "ସରପଞ୍ଚ କିମ୍ବା ନାଗରିକଙ୍କ ରୋଲ୍ ବଦଳାଇ ସ୍ୱୟଂଚାଳିତ ବାର୍ତ୍ତାର ଯାଞ୍ଚ କରନ୍ତୁ:",
    villagerDesc: "ଅଭିଯୋଗ କରିପାରିବେ, ସମର୍ଥନ କରିପାରିବେ ଏବଂ ମଣ୍ଡିରେ ସାମଗ୍ରୀ ବିକ୍ରି ବିଜ୍ଞାପନ ଦେଇପାରିବେ",
    pradhanDesc: "ସମସ୍ୟାର ସମାଧାନ ସ୍ଥିତି ବଦଳାଇପାରିବେ ଓ ଗ୍ରାମରେ ଜରୁରୀ ସୂଚନା ଦେଇପାରିବେ",
    newAccount: "ଫୋନ୍ ନମ୍ବର ଯାଞ୍ଚ",
    nameLabel: "ପୂରା ନାମ",
    phoneLabel: "୧୦ ଅଙ୍କର ମୋବାଇଲ୍ ନମ୍ବର",
    roleLabel: "ପସନ୍ଦର ଭୂମିକା",
    residentRole: "ଗ୍ରାମବାସୀ ସଦସ୍ୟ",
    pradhanRole: "ଗ୍ରାମ ମୁଖ୍ୟ / ସରପଞ୍ଚ",
    otpSend: "ଓଟିପି ପଠାନ୍ତୁ",
    otpCodeMsg: "ଯାଞ୍ଚ କୋଡ୍ ପଠାଗଲା। ଟେଷ୍ଟ ପାଇଁ 1234 ବ୍ୟବହାର କରନ୍ତୁ:",
    verifyCode: "କୋଡ୍ ଯାଞ୍ଚ କରନ୍ତୁ",
    cancel: "ରଦ୍ଦ କରନ୍ତୁ",
    activeCredentials: "ବର୍ତ୍ତମାନର ଲଗଇନ୍ ସୂଚନା",
    actionReport: "ଅଭିଯୋଗ ସମାଧାନ ମ୍ୟାଟ୍ରିକ୍ସ",
    statusSelect: "ସମାଧାନର ସ୍ତର",
    notesLabel: "ସରକାରୀ ସମାଧାନ ଟିପ୍ପଣୀ",
    notesPlaceholder: "ଯେପରିକି: ପାନୀୟ ଜଳ ପାଇପଲାଇନ ସଜଡା ସରିଛି। ଜଳଯୋଗାଣ ସ୍ୱାଭାବିକ।",
    webhookDesc: "ସମାଧାନ ସରିଲେ, ଅଭିଯୋਗକାରୀଙ୍କୁ ସ୍ୱୟଂଚାଳିତ ଭାବେ ହ୍ୱାଟ୍ସଆପ୍ ଏସଏମଏସ ଯିବ।",
    saveChanges: "ବଦଳାବ ସଂରକ୍ଷଣ କରନ୍ତୁ",
    allCategories: "ସମସ୍ତ ଶ୍ରେଣୀ",
    contactSms: "ଯୋଗାଯୋଗ କରନ୍ତୁ / SMS",
    loginToContact: "ଦେଖିବା ପାଇଁ ଲଗଇନ୍ କରନ୍ତୁ",
    farmersGroup: "🌾 କୃଷକ ମଞ୍ଚ",
    youthGroup: "🤝 ଯୁବ କ୍ଲବ୍",
    womenGroup: "👩 ମହିଳା ସ୍ୱୟଂ ସହାୟିକା ଗୋଷ୍ଠୀ (SHG)",
    generalGroup: "💬 ସାଧାରଣ ମଞ୍ଚ"
  },
  pa: {
    appName: "ਗ੍ਰਾਮ ਸਵਰਾਜ ਮੋਬਾਈਲ",
    appSubName: "ਪੇਂਡੂ ਵਿਕਾਸ ਅਤੇ ਮੰਡੀ ਬੋਰਡ",
    alertFeed: "ਐਮਰਜੈਂਸੀ ਅਲਰਟ",
    homeTab: "ਪੰਚਾਇਤ ਫੀਡ",
    reportTab: "ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ",
    marketTab: "ਮੰਡੀ ਬੋਰਡ",
    groupsTab: "ਪੇਂਡੂ ਸਮੂਹ",
    profileTab: "ਪ੍ਰੋਫਾਈਲ",
    anonymous: "ਗੁਪਤ (ਗੁਮਨਾਮ)",
    postAnonymously: "ਗੁਪਤ ਰੂਪ ਵਿੱਚ ਪੋਸਟ ਕਰੋ",
    anonymousHint: "ਤੁਹਾਡਾ ਨਾਮ ਜਨਤਕ ਫੀਡ ਅਤੇ ਆਮ ਪਿੰਡ ਵਾਸੀਆਂ ਤੋਂ ਲੁਕਾਇਆ ਜਾਵੇਗਾ।",
    phoneLogin: "ਓਟੀਪੀ ਵੈਰੀਫਿਕੇਸ਼ਨ",
    notVerified: "ਪੈਂਡਿੰਗ ਵੈਰੀਫਿਕੇਸ਼ਨ",
    activeUser: "ਕਿਰਿਆਸ਼ੀਲ ਪ੍ਰੋਫਾਈਲ",
    changeStatus: "ਸਟੇਟਸ ਬਦਲੋ",
    upvoteBtn: "ਮੈਨੂੰ ਵੀ ਇਹ ਸਮੱਸਿਆ ਹੈ",
    commentsTitle: "ਵਿਚਾਰ-ਵਟਾਂਦਰਾ",
    addComment: "ਟਿੱਪਣੀ ਲਿਖੋ",
    marketGoods: "ਫ਼ਸਲਾਂ ਅਤੇ ਸਾਮਾਨ",
    marketServices: "ਟਰੈਕਟਰ / ਖੇਤੀ ਸੇਵਾਵਾਂ",
    marketJobs: "ਦਿਹਾੜੀ ਅਤੇ ਰੁਜ਼ਗਾਰ",
    addListing: "ਨਵਾਂ ਇਸ਼ਤਿਹਾਰ",
    jobWage: "ਕੀਮਤ / ਦਿਹਾੜੀ",
    contact: "ਸੰਪਰਕ ਲਈ ਲਾਗਇਨ ਕਰੋ",
    anonymousPlaceholder: "ਗੁਪਤ ਪਿੰਡ ਵਾਸੀ",
    villageSelection: "ਚੁਣਿਆ ਪਿੰਡ",
    resolvedSms: "ਸ਼ਿਕਾਇਤਕਰਤਾ ਨੂੰ SMS ਭੇਜਿਆ",
    noComments: "ਅਜੇ ਤੱਕ ਕੋਈ ਵਿਚਾਰ ਨਹੀਂ ਹੋਇਆ।",
    writeOpinion: "ਆਪਣੀ ਰਾਏ ਲਿਖੋ...",
    notifFirst: "ਟਿੱਪਣੀ ਲਿਖਣ ਲਈ ਪ੍ਰੋਫਾਈਲ 'ਚ ਜਾ ਕੇ ਲਾਗਇਨ ਕਰੋ।",
    reportLoginRequired: "ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰਨ ਲਈ ਮੋਬਾਈਲ ਵੈਰੀਫਿਕੇਸ਼ਨ ਲਾਜ਼ਮੀ ਹੈ।",
    directForums: "ਵਿਸ਼ੇਸ਼ ਪੇਂਡੂ ਸਭਾ",
    villageGroups: "ਪੰਚਾਇਤੀ ਸਮੂਹ ਚਰਚਾ",
    emptyGroup: "ਇਸ ਗਰੁੱਪ ਵਿੱਚ ਅਜੇ ਤੱਕ ਕੋਈ ਚੈਟ ਨਹੀਂ ਹੋਈ। ਪਹਿਲਾਂ ਤੁਸੀਂ ਲਿਖੋ!",
    anonymousMode: "ਗੁਪਤ ਮੋਡ",
    typeGroupMessage: "ਸੁਨੇਹਾ ਲਿਖੋ...",
    groupLoginRequired: "ਚਰਚਾ ਵਿੱਚ ਹਿੱਸਾ ਲੈਣ ਲਈ ਫੋਨ ਲਾਗਇਨ ਜ਼ਰੂਰੀ ਹੈ।",
    otpCredentials: "ਸੁਰੱਖਿਅਤ ਓਟੀਪੀ ਗੇਟਵੇ",
    sandboxHeader: "ਟੈਸਟਿੰਗ ਸੈਂਡਬੌਕਸ (Sandbox)",
    sandboxDesc: "ਸਰਪੰਚ ਜਾਂ ਨਾਗਰਿਕ ਬਣ ਕੇ ਆਟੋ-ਐਸਐਮਐਸ ਚੈੱਕ ਕਰੋ:",
    villagerDesc: "ਸ਼ਿਕਾਇਤ ਕਰ ਸਕਦੇ ਹਨ, ਮੰਡੀ ਵਿੱਚ ਇਸ਼ਤਿਹਾਰ ਦੇ ਸਕਦੇ ਹਨ",
    pradhanDesc: "ਸ਼ਿਕਾਇਤਾਂ ਦਾ ਹੱਲ ਕਰ ਸਕਦੇ ਹਨ ਅਤੇ ਪੂਰੇ ਪਿੰਡ ਨੂੰ ਅਲਰਟ ਭੇਜ ਸਕਦੇ ਹਨ",
    newAccount: "ਮੋਬਾਈਲ ਨੰਬਰ ਵੈਰੀਫਿਕੇਸ਼ਨ",
    nameLabel: "ਪੂਰਾ ਨਾਮ",
    phoneLabel: "10 ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ",
    roleLabel: "ਖਾਤੇ ਦਾ ਰੋਲ",
    residentRole: "ਪਿੰਡ ਨਿਵਾਸੀ",
    pradhanRole: "ਸਰਪੰਚ / ਗ੍ਰਾਮ ਪ੍ਰਧਾਨ (Village Head)",
    otpSend: "ਓਟੀਪੀ ਪ੍ਰਾਪਤ ਕਰੋ",
    otpCodeMsg: "ਵੈਰੀਫਿਕੇਸ਼ਨ ਕੋਡ ਭੇਜਿਆ ਗਿਆ! ਟੈਸਟ ਲਈ 1234 ਭਰੋ:",
    verifyCode: "ਕੋਡ ਦੀ ਜਾਂਚ ਕਰੋ",
    cancel: "ਰੱਦ ਕਰੋ",
    activeCredentials: "ਮੌਜੂਦਾ ਲਾਗਇਨ ਜਾਣਕਾਰੀ",
    actionReport: "ਸ਼ਿਕਾਇਤ ਨਿਵਾਰਨ ਕਾਰਵਾਈ",
    statusSelect: "ਹੱਲ ਦਾ ਪੜਾਅ",
    notesLabel: "ਕਾਰਵਾਈ ਰਿਪੋਰਟ ਨੋਟਸ",
    notesPlaceholder: "ਜਿਵੇਂ: ਟਿਊਬਵੈੱਲ ਦੀ ਮੋਟਰ ਠੀਕ ਕਰ ਦਿੱਤੀ ਗਈ ਹੈ, ਪਾਣੀ ਸਪਲਾਈ ਚਾਲੂ ਹੈ।",
    webhookDesc: "ਹੱਲ ਹੋਣ 'ਤੇ, ਸਿਸਟਮ ਨਿਵਾਸੀ ਨੂੰ ਤੁਰੰਤ ਵਟਸਐਪ ਐਸਐਮਐਸ ਭੇਜੇਗਾ।",
    saveChanges: "ਬਦਲਾਅ ਸੁਰੱਖਿਅਤ ਕਰੋ",
    allCategories: "ਸਭ ਸ਼੍ਰੇਣੀਆਂ",
    contactSms: "ਸੰਪਰਕ ਕਰੋ / SMS",
    loginToContact: "ਦੇਖਣ ਲਈ ਲਾਗਇਨ ਕਰੋ",
    farmersGroup: "🌾 ਕਿਸਾਨ ਵੀਰ",
    youthGroup: "🤝 ਨੌਜਵਾਨ ਸਭਾ",
    womenGroup: "👩 ਔਰਤਾਂ ਦਾ ਸਵੈ-ਸਹਾਇਤਾ ਗਰੁੱਪ (SHG)",
    generalGroup: "💬 ਆਮ ਚੌਪਾਲ"
  },
  as: {
    appName: "গ্ৰাম স্বৰাজ ম’বাইল",
    appSubName: "গ্ৰামোন্নয়ন আৰু মণ্ডি বোৰ্ড",
    alertFeed: "জৰুৰী জাননী",
    homeTab: "মুখ্য ফীড",
    reportTab: "অভিযোগ নথীভুক্ত কৰক",
    marketTab: "মণ্ডি বজাৰ",
    groupsTab: "গ্ৰাম্য গোট",
    profileTab: "প্ৰ’ফাইল",
    anonymous: "অজ্ঞাত",
    postAnonymously: "নামবিহীন ভাৱে প‍’ষ্ট কৰক",
    anonymousHint: "জনসাধাৰণৰ সন্মুখত আপোনাৰ নাম সদায় গোপন ৰখা হ’ব।",
    phoneLogin: "ওটিপি সত্যাপন",
    notVerified: "অপৰীক্ষিত একাউণ্ট",
    activeUser: "সক্ৰিয় প্ৰ’ফাইল",
    changeStatus: "স্থিতি সলনি কৰক",
    upvoteBtn: "মোৰো একেই সমস্যা আছে",
    commentsTitle: "আলোচনা",
    addComment: "মন্তব্য কৰক",
    marketGoods: "উৎপাদিত সামগ্ৰী",
    marketServices: "সেৱা / ভাড়ালৈ",
    marketJobs: "দৈনিক হাজিৰা কাম",
    addListing: "নতুন বিজ্ঞাপন",
    jobWage: "মূল্য বা মজুৰি",
    contact: "যোগাযোগ কৰিবলৈ ল’গইন কৰক",
    anonymousPlaceholder: "নামবিহীন গ্ৰামবাসী",
    villageSelection: "সক্ৰিয় ভিলেজ",
    resolvedSms: "অভিযোগকাৰীলৈ নিশ্চিতকৰণ বাৰ্তা প্ৰেৰণ কৰা হ’ল",
    noComments: "এতিয়ালৈকে কোনো আলোচনা হোৱা নাই।",
    writeOpinion: "আপোনাৰ মতামত লিখক...",
    notifFirst: "মন্তব্য কৰিবলৈ অনুগ্ৰহ কৰি প্ৰ’ফাইলত মোবাইল ল’গইন কৰক।",
    reportLoginRequired: "অভিযোগ দাখিল কৰিবলৈ সত্যতা নিৰূপণ প্ৰয়োজনীয়।",
    directForums: "বিশেষ ভিলেজ চৌপাল",
    villageGroups: "গ্ৰাম সভা গোট চ্যাট",
    emptyGroup: "এই গোটত এতিয়ালৈকে কোনো বাৰ্তা পঠোৱা হোৱা নাই।",
    anonymousMode: "নাম গোপন ৰাখক",
    typeGroupMessage: "বাৰ্তা লিখক...",
    groupLoginRequired: "বাৰ্তা প্ৰেৰণ কৰিবলৈ ওটিপি ল’গইন নিশ্চিত কৰক।",
    otpCredentials: "সুৰক্ষিত ওটিপি দুৱাৰ",
    sandboxHeader: "চেণ্ডবক্স টেস্টিং পেনেল",
    sandboxDesc: "ভিউ সলনি কৰক আৰু হোৱাটচেপ-এছএমএছৰ কাম চকু ফুৰাওক:",
    villagerDesc: "অভিযোগ দাখিল কৰিব পাৰে আৰু মণ্ডি বজাৰত প’ষ্ট কৰিব পাৰে",
    pradhanDesc: "অভিযোগৰ স্তৰ সলাব পাৰে আৰু আটাইকে সুৰক্ষিত ৰাখিবলৈ সতৰ্কবাণী দিব পাৰে",
    newAccount: "নতুন নামভৰ্তি (ওটিপি)",
    nameLabel: "সম্পূৰ্ণ নাম",
    phoneLabel: "১০ টা সংখ্যাৰ মোবাইল নম্বৰ",
    roleLabel: "নিৰ্বাচিত ভূমিকা",
    residentRole: "গ্ৰামবাসী সদস্য",
    pradhanRole: "গ্ৰাম প্ৰধান (সভাপতি)",
    otpSend: "ওটিপি পঠাওক",
    otpCodeMsg: "সত্যাপন ক’ড পঠিওৱা হ’ল। টেষ্ট কৰিবলৈ 1234 লিখক:",
    verifyCode: "ক’ড মিলক",
    cancel: "বাতিল কৰক",
    activeCredentials: "বৰ্তমানৰ একাউণ্ট ডাটা",
    actionReport: "অভিযোগ সমাধান সমিতি",
    statusSelect: "সমাধানৰ স্থিতি",
    notesLabel: "কাৰ্যকাৰী চৰকাৰী টোকা",
    notesPlaceholder: "যেনে: পানীৰ মূল পাইপৰ কেণা ভাঙি যোৱাত মেৰামতি কৰা হ’ল। পানী যোগান আৰম্ভ।",
    webhookDesc: "সমাধান হ’লে ম’বাইল গ্ৰাহকলৈ স্বয়ংক্ৰিয় বাৰ্তা প্ৰেৰণ কৰা হ’ব।",
    saveChanges: "বদলবোৰ সাঁচি থওক",
    allCategories: "সকলো শ্ৰেণী",
    contactSms: "যোগাযোগ কৰক / এছএমএছ",
    loginToContact: "ফ’ন নম্বৰ চাবলৈ ল’গইন কৰক",
    farmersGroup: "🌾 কৃষক গোট",
    youthGroup: "🤝 যুৱ সংঘ",
    womenGroup: "👩 আত্মসহায়ক গোট (SHG)",
    generalGroup: "💬 সাধাৰণ মেল"
  },
  sa: {
    appName: "ग्रामस्वराज्य मञ्च:",
    appSubName: "ग्रामविकासः हट्टविपण्यं च",
    alertFeed: "आपातकालीना सूचना",
    homeTab: "मुख्यपृष्ठम्",
    reportTab: "पञ्जीकरणम्",
    marketTab: "विपणि मण्डली",
    groupsTab: "समूहाः",
    profileTab: "व्यक्तिगतम्",
    anonymous: "गुप्तरूपम्",
    postAnonymously: "गुप्तरूपेण सूचयतु",
    anonymousHint: "भवतः नाम सार्वजनिकफलके अन्य ग्रामेभ्यः सर्वथा अदृश्यं भविष्यति।",
    phoneLogin: "ओटीपी-प्रवेशः",
    notVerified: "अप्रमाणित-पत्रम्",
    activeUser: "सक्रिय-रूपम्",
    changeStatus: "स्थितिपरिवर्तनम्",
    upvoteBtn: "ममापि एषा समस्या",
    commentsTitle: "चर्चा",
    addComment: "टिप्पणीं लिखतु",
    marketGoods: "उत्पादितद्रव्याणि",
    marketServices: "कृषिकायाणि",
    marketJobs: "प्रतिदिनभृतिः",
    addListing: "नवीनं विज्ञापनम्",
    jobWage: "मूल्यम् / भृतिः",
    contact: "सम्पर्कं कर्तुं प्रविशतु",
    anonymousPlaceholder: "गुप्तग्रामवासी",
    villageSelection: "चित ग्रामः",
    resolvedSms: "सन्देशः प्रेषितः",
    noComments: "न कापि टिप्पणी अस्ति।",
    writeOpinion: "स्वकीयं मतिं लिखतु...",
    notifFirst: "टिप्पणी लेखनाय पूर्वं मुख्यप्रवेशं कुरुत।",
    reportLoginRequired: "दोष निवेदनाथं प्रमाणीकरणम् आवश्यकम्।",
    directForums: "ग्राम चौपाल संवादः",
    villageGroups: "समूह सम्भाषणम्",
    emptyGroup: "अस्मिन् समूहे न कोऽपि सन्देशः अस्ति। प्रथमं लिखतु!",
    anonymousMode: "अनाम प्रकारः",
    typeGroupMessage: "समूहे वार्तां लिखतु...",
    groupLoginRequired: "वार्ता प्रेषणाय फोन सत्यापनं अनिवार्यम्।",
    otpCredentials: "सुरक्षित प्रमाणीकरण द्वारम्",
    sandboxHeader: "परीक्षण पटलम्",
    sandboxDesc: "प्रधानस्य अथवा सामान्यजनस्य स्थानं स्वीकृत्य एसएमएस व्यवस्थां पश्यतु:",
    villagerDesc: "फरियाद करोति, कृषिवस्तूनि विक्रीयते च",
    pradhanDesc: "दोषस्य स्थितिं परिवर्तयितुं शक्नोति आपातकालीनां सूचनां प्रेषयति च",
    newAccount: "नूतन प्रवेशः (ओटीपी)",
    nameLabel: "पूर्णं नाम",
    phoneLabel: "दशाङ्की दूरभाष सङ्ख्या",
    roleLabel: "अपेक्षितं स्थानम्",
    residentRole: "ग्रामवासी",
    pradhanRole: "सरपञ्चः / ग्राम प्रधानः",
    otpSend: "ओटीपी प्रेषयतु",
    otpCodeMsg: "परीक्षणार्थं 1234 इति कोड लिखतु:",
    verifyCode: "सत्यापयतु",
    cancel: "निरसनम्",
    activeCredentials: "सक्रिय प्रवेश विवरणम्",
    actionReport: "समीकरण योजना",
    statusSelect: "निवारण स्थितिः",
    notesLabel: "विस्तृत विवरणानि",
    notesPlaceholder: "उदा: विद्युत् संवाहक तारं सुव्यवस्थित अस्ति।",
    webhookDesc: "समाधाने कृते सति ग्रामवासाय स्वयमेव संदेशः प्रेषितः भविष्यति।",
    saveChanges: "सुरक्षितं कुरु",
    allCategories: "सर्वे वर्गाः",
    contactSms: "सम्पर्कः / SMS",
    loginToContact: "द्रष्टुं प्रवेशं कुरु",
    farmersGroup: "🌾 कृषक परिषद्",
    youthGroup: "🤝 युवा सङ्घः",
    womenGroup: "👩 महिला स्वावलम्बनम्",
    generalGroup: "💬 सामान्य विचारः"
  },
  bho: {
    appName: "ग्रामस्वराज मोबाइल",
    appSubName: "खेती-बारी आ मंडी बोर्ड",
    alertFeed: "आपातकालीन चेतावनी",
    homeTab: "मुख्य चर्चा Feed",
    reportTab: "शिकायत लिखीं",
    marketTab: "मंडी बाजार",
    groupsTab: "ग्राम चौपाल",
    profileTab: "प्रोफाइल",
    anonymous: "गुप्त (पर्दा में)",
    postAnonymously: "बिना नाम के पोस्ट करीं",
    anonymousHint: "रउआ नाम सउसे गाँव के मोबाइल स्क्रीन से पूरी तरह से लुका जाई।",
    phoneLogin: "ओटीपी से लॉगिन",
    notVerified: "खाता जाँचल बाकी",
    activeUser: "एक्टिव प्रोफाइल",
    changeStatus: "काम के दर्जा बदलीं",
    upvoteBtn: "हमारो इहें समस्या बा",
    commentsTitle: "बात-चीत",
    addComment: "अपनी बात लिखीं",
    marketGoods: "अनाज आ देहाती सामान",
    marketServices: "ट्रैक्टर / कृषि सेवा",
    marketJobs: "मजदूरी आ दरमाहा",
    addListing: "नया प्रचार जोड़ीं",
    jobWage: "दाम / रोजी बनिहार",
    contact: "बतियावे खातिर लॉगिन करीं",
    anonymousPlaceholder: "गुप्त देहाती भाई",
    villageSelection: "सक्रिय गाँव",
    resolvedSms: "निवारण के SMS भेजल गइल",
    noComments: "कउनो बात-चीत कइल नइखे गइल।",
    writeOpinion: "अपनी बात लिखीं...",
    notifFirst: "कमेंट करे खातिर पाहिले ओटिपी से प्रोफाइल में जाके लॉगिन करीं।",
    reportLoginRequired: "शिकायत दर्ज करे खातिर मोबाईल वेरिफ़िकेशन करववल जरूरी बा।",
    directForums: "ख़ास गँवई चौपाल",
    villageGroups: "ग्राम पंचायत समूह बात-चीत",
    emptyGroup: "ई चौपाल पे केहू संदेश नइखे लिखले। रउआ पाहिले लिखीं!",
    anonymousMode: "अनाम मोड",
    typeGroupMessage: "चौपाल पे संदेश लिखीं...",
    groupLoginRequired: "चर्चा में शामिल होखे खातिर फोन नंबर लॉगिन जरूरी बा।",
    otpCredentials: "सुरक्षित मोबाईल ओटीपी",
    sandboxHeader: "टेस्टिंग यंत्र (Sandbox)",
    sandboxDesc: "मुखिया जी या ग्रामीण बनके एसएमएस जाँचीं:",
    villagerDesc: "शिकायत कर सकेलें आ मंडी में बेचे खातिर प्रचार लगा सकेलें",
    pradhanDesc: "शिकायत के सुधारे वाला दर्जा बदल सकेलें आ गाँव खातिर निर्देश जारी कर सकेलें",
    newAccount: "नया मोबाइल नंबर के जांच",
    nameLabel: "पूरा नाम",
    phoneLabel: "१० गो अंक के मोबाईल नम्बर",
    roleLabel: "चुनाइल भूमिका",
    residentRole: "गाँव के सदस्य",
    pradhanRole: "ग्राम प्रधान / मुखिया जी",
    otpSend: "ओटीपी मँगाईं",
    otpCodeMsg: "वेरिफिकेशन कोड भेजल गइल! रउआ जांच खातिर 1234 लिखीं:",
    verifyCode: "ओटीपी जाँचीं",
    cancel: "रद्द करीं",
    activeCredentials: "अभिन के लॉगिन जानकारी",
    actionReport: "शिकायत सुधारे वाला कमिटी",
    statusSelect: "काम कहाँ पहुँचल",
    notesLabel: "अफसर के सुधारे वाला विवरण",
    notesPlaceholder: "जइसे: पानी के कल के पाइप ठीक कइ देहल गइल बा। पानी आवे लागल बा।",
    webhookDesc: "काम पूरा होत ही, मेक आ जॅपियर से देहाती भाई के मोबईल पे सीधे मैसेज चल जाई।",
    saveChanges: "अपडेट सुरक्षित करीं",
    allCategories: "कुल श्रेणी",
    contactSms: "सम्पर्क करीं / SMS",
    loginToContact: "देखे खातिर लॉगिन करीं",
    farmersGroup: "🌾 किसान भाई मंच",
    youthGroup: "🤝 गँवई नौजवान",
    womenGroup: "👩 दीदी लोगन के बचत समूह",
    generalGroup: "💬 आम समस्या संकट"
  },
  mai: {
    appName: "ग्रामस्वराज मिथिला",
    appSubName: "कृषि विकास आ मंडी बोर्ड",
    alertFeed: "आपातकालीन सूचना",
    homeTab: "मुख्य चौपाल फीड",
    reportTab: "शिकायत दर्ज़ करू",
    marketTab: "मंडी बाजार",
    groupsTab: "पंचायत समूह चर्चा",
    profileTab: "प्रोफाइल विवरणी",
    anonymous: "गुप्त (अनाम)",
    postAnonymously: "नाम छुपाय क पोस्ट करू",
    anonymousHint: "अहाँक नाम आम लोग आ स्क्रीन स पूर्णतः नुका क राखल जायत।",
    phoneLogin: "ओटीपी सँ लॉगिन करू",
    notVerified: "जाँच हेबाक बाकी",
    activeUser: "सक्रिय प्रोफाइल",
    changeStatus: "स्थिति परिवर्तित करू",
    upvoteBtn: "हमरो इहै समस्या अछि",
    commentsTitle: "आपसी विमर्श",
    addComment: "अपन विचार दियू",
    marketGoods: "अनाज आ गामक दूध-दही",
    marketServices: "ट्रैक्टर आ किसानी सेवा",
    marketJobs: "कुली-बनिहार आ मजदूरी",
    addListing: "नया विज्ञापन जोड़ीं",
    jobWage: "कीमत आ रोजाना बनिहारी",
    contact: "संपर्क करबाक लेल लॉगिन करू",
    anonymousPlaceholder: "कल्याण गामक हितैषी",
    villageSelection: "चयनित गाम",
    resolvedSms: "निवारणक सूचना प्रेषित",
    noComments: "कोनो विमर्श नै भेल अछि।",
    writeOpinion: "अपन विचार दियू...",
    notifFirst: "टिप्पणी लिखबाक लेल प्रोफाइल म जाक लॉगिन करू।",
    reportLoginRequired: "शिकायत दर्ज़ करबाक लेल मोबाईल नंबरक सत्यापन अनिवार्य अछि।",
    directForums: "पंचायत विशेष चौपाल",
    villageGroups: "गामक समूह चर्चा सभा",
    emptyGroup: "एहि चौपाल पर कोनो संदेश नै अछि। अहीं स शुरुआत करू!",
    anonymousMode: "अनाम मोड (Hide Name)",
    typeGroupMessage: "चौपाल संदेश लिखू...",
    groupLoginRequired: "गामक चर्चा म शामिल हेबाक लेल फोन सत्यापन अनिवार्य अछि।",
    otpCredentials: "सुरक्षित ओटीपी लॉगिन तंत्र",
    sandboxHeader: "टेस्टिंग टूल्स (Sandbox)",
    sandboxDesc: "मुखिया वा ग्रामीण सदस्यक भूमिका बदलि कएसएमएस संसूचक जाँचीं:",
    villagerDesc: "शिकायत दर्ज़ आ वोट क सकैत छथि, मंडी म सामान बेच क विज्ञापन द सकैत छथि",
    pradhanDesc: "शिकायतक निवारण स्थिति परिवर्तित क सकैत छथि आ गाम म सूचना जारी क सकैत छथि",
    newAccount: "नया मोबाइल नंबरक सत्यापन",
    nameLabel: "पूरा नाम",
    phoneLabel: "१० टा संख्याक मोबाईल",
    roleLabel: "चयनित भूमिका",
    residentRole: "गामक नागरिक",
    pradhanRole: "सरपञ्च / मुखिया जी (Village Head)",
    otpSend: "ओटीपी मँगाऊ",
    otpCodeMsg: "सत्यापन कोड भेजल गेल। टेस्टक लेल 1234 लिखू:",
    verifyCode: "कोड सत्यापित करू",
    cancel: "रद्द करू",
    activeCredentials: "अखनुक लॉगिन विवरणी",
    actionReport: "निवारण समीक्षा बोर्ड",
    statusSelect: "निवारणक स्थिति",
    notesLabel: "निवारणक विवरणी नोट्स",
    notesPlaceholder: "जहिना: नल दुरुस्त क देल गेल अछि। पेयजल सुचारू चालू अछि।",
    webhookDesc: "निवारण हेतहि, ग्रामीणक मोबाईल पर जैपियर द्वारा त्वरित संदेश चलि जायत।",
    saveChanges: "बदलाव स्वीकार करू",
    allCategories: "सभ श्रेणी",
    contactSms: "सम्पर्क करू / SMS",
    loginToContact: "देखबा लेल लॉगिन करू",
    farmersGroup: "🌾 मिथिला कृषक मंच",
    youthGroup: "🤝 मैथिल युवा क्लब",
    womenGroup: "👩 महिला बचत समिति",
    generalGroup: "💬 गामक सामान्य विमर्श"
  },
  es: {
    appName: "GramSwaraj Móvil",
    appSubName: "Desarrollo Cívico y Mercado Mandi",
    alertFeed: "Alertas de Emergencia",
    homeTab: "Inicio",
    reportTab: "Nueva Denuncia",
    marketTab: "Mercado Local",
    groupsTab: "Grupos Locales",
    profileTab: "Mi Perfil",
    anonymous: "Anónimo",
    postAnonymously: "Publicar de manera anónima",
    anonymousHint: "Su nombre se ocultará en las transmisiones públicas para los aldeanos.",
    phoneLogin: "Verificación por OTP",
    notVerified: "Cuenta sin verificar",
    activeUser: "Perfil Activo",
    changeStatus: "Cambiar Estado",
    upvoteBtn: "Yo también tengo este problema",
    commentsTitle: "Diálogo",
    addComment: "Agregar comentario",
    marketGoods: "Productos / Cosecha",
    marketServices: "Servicios Agrícolas",
    marketJobs: "Trabajo Diario / Empleo",
    addListing: "Agregar Clasificado",
    jobWage: "Precio o Salario",
    contact: "Iniciar sesión para contactar",
    anonymousPlaceholder: "Aldeano Anónimo",
    villageSelection: "Municipio Activo",
    resolvedSms: "Notificación SMS webhook enviada",
    noComments: "Aún no hay comentarios.",
    writeOpinion: "Escriba un comentario...",
    notifFirst: "Inicie sesión con OTP en Perfil para comentar.",
    reportLoginRequired: "Se requiere verificación de teléfono para enviar informes.",
    directForums: "Foros Comunitarios Directos",
    villageGroups: "Conversación de Grupos de la Aldea",
    emptyGroup: "No hay comentarios en este grupo. ¡Sea el primero en escribir!",
    anonymousMode: "Modo anónimo",
    typeGroupMessage: "Escriba un mensaje para el grupo...",
    groupLoginRequired: "Se requiere autorización OTP para enviar mensajes.",
    otpCredentials: "Ingreso de Credenciales OTP Seguras",
    sandboxHeader: "Panel de Prueba de Roles",
    sandboxDesc: "Cambie de rol al instante para probar el flujo de SMS y restricciones de administrador:",
    villagerDesc: "Puede enviar quejas, votar y publicar anuncios clasificados de venta",
    pradhanDesc: "Modifica el estado de quejas y emite alertas de transmisiones de emergencia",
    newAccount: "Ingreso Interactivo por Teléfono/OTP",
    nameLabel: "Nombre Completo",
    phoneLabel: "Móvil de 10 dígitos",
    roleLabel: "Rol de Cuenta deseado",
    residentRole: "Residente",
    pradhanRole: "Jefe de la Aldea (Gram Pradhan)",
    otpSend: "Enviar código OTP",
    otpCodeMsg: "Código de prueba enviado. Use 1234 para pruebas sandbox:",
    verifyCode: "Verificar Código",
    cancel: "Cancelar",
    activeCredentials: "DATOS DEL PERFIL INICIADO",
    actionReport: "Matriz de Resolución de Despacho",
    statusSelect: "Nivel de Resolución",
    notesLabel: "Nota de acción gubernamental",
    notesPlaceholder: "Ej., Fusible del transformador cambiado. Líneas de alimentación re-ancladas.",
    webhookDesc: "Al seleccionar 'Resolved', se activará un webhook automático para enviar SMS WhatsApp al reportero cívico.",
    saveChanges: "Actualizar Estado Administrativo",
    allCategories: "Todas categorías",
    contactSms: "Contacto / SMS",
    loginToContact: "Inicia sesión para ver",
    farmersGroup: "🌾 Foro de Agricultores",
    youthGroup: "🤝 Club de Jóvenes",
    womenGroup: "👩 Asociación de Mujeres (SHG)",
    generalGroup: "💬 Foro General"
  },
  fr: {
    appName: "GramSwaraj Mobile",
    appSubName: "Développement Villageois & Mandi",
    alertFeed: "Alertes d'Urgence",
    homeTab: "Fils d'actualité",
    reportTab: "Dépôt d'incident",
    marketTab: "Marché Local",
    groupsTab: "Groupes Villageois",
    profileTab: "Profil",
    anonymous: "Anonyme",
    postAnonymously: "Publier anonymement",
    anonymousHint: "Votre nom sera masqué sur les fils publics pour les villageois standard.",
    phoneLogin: "Connexion OTP",
    notVerified: "Compte non certifié",
    activeUser: "Profil Actif",
    changeStatus: "Modifier Statut",
    upvoteBtn: "J'ai aussi ce problème",
    commentsTitle: "Dialogue",
    addComment: "Commenter",
    marketGoods: "Produits / Récoltes",
    marketServices: "Services / Tracteur",
    marketJobs: "Emploi / Salaire journalier",
    addListing: "Créer une annonce",
    jobWage: "Prix / Rémunération",
    contact: "Connectez-vous pour contacter",
    anonymousPlaceholder: "Membre Anonyme",
    villageSelection: "Village Actif",
    resolvedSms: "Notification SMS webhook dirigée",
    noComments: "Aucun commentaire pour le moment.",
    writeOpinion: "Écrire une opinion...",
    notifFirst: "Authentification requise pour commenter. Connectez-vous.",
    reportLoginRequired: "Vérification téléphonique requise pour poster un problème.",
    directForums: "Forums de Discussion Spéciaux",
    villageGroups: "Dialogue du Conseil Villageois",
    emptyGroup: "La discussion est vide. Écrivez le premier message !",
    anonymousMode: "Mode anonyme",
    typeGroupMessage: "Écrire un message au groupe...",
    groupLoginRequired: "Connexion OTP requise pour rédiger un message.",
    otpCredentials: "Portail de Connexion Sécurisé OTP",
    sandboxHeader: "Console de Test (Sandbox)",
    sandboxDesc: "Simulez un profil résident ou chef de village pour valider les SMS et droits de modération :",
    villagerDesc: "Peut soumettre et voter pour des griefs, et publier des annonces de vente",
    pradhanDesc: "Peut modifier le statut des incidents et émettre des alertes broadcasts",
    newAccount: "Vérification Téléphonique Native",
    nameLabel: "Nom Complet",
    phoneLabel: "Numéro de Téléphone (10 chiffres)",
    roleLabel: "Rôle Demandé",
    residentRole: "Résident / Citoyen",
    pradhanRole: "Chef de Village (Gram Pradhan)",
    otpSend: "Envoyer le code OTP",
    otpCodeMsg: "Code temporaire transmis. Entrez 1234 pour tester :",
    verifyCode: "Vérifier Code",
    cancel: "Annuler",
    activeCredentials: "INFORMATIONS D'IDENTIFICATION COMPTE",
    actionReport: "Matrice d'attribution d'Incident",
    statusSelect: "Étape de Résolution",
    notesLabel: "Notes de Résolution du Bureau",
    notesPlaceholder: "Ex: Câble électrique réparé de façon sécurisée près de l'école.",
    webhookDesc: "La sélection de 'Resolved' déclenche automatiquement un webhook Zapier vers le reporter par SMS.",
    saveChanges: "Mettre à jour l'Incident",
    allCategories: "Toutes catégories",
    contactSms: "Contacter / SMS",
    loginToContact: "S'identifier pour voir",
    farmersGroup: "🌾 Forum des Agriculteurs",
    youthGroup: "🤝 Conseil des Jeunes",
    womenGroup: "👩 Groupe d'Entraide Féminin",
    generalGroup: "💬 Forum Général"
  },
  ar: {
    appName: "جرام سواراج للهاتف",
    appSubName: "التنمية الريفية ومجلس السوق",
    alertFeed: "تنبيهات الطوارئ",
    homeTab: "الجريدة العامة",
    reportTab: "تقديم شكوى",
    marketTab: "مجلس السوق (المندى)",
    groupsTab: "مجموعات القرية",
    profileTab: "الملف الشخصي",
    anonymous: "مجهول الاسم",
    postAnonymously: "نشر باسم مستعار مجهول",
    anonymousHint: "سيتم إخفاء اسمك بالكامل من الشاشات وأمام جمهور أهل القرية لحمايتك.",
    phoneLogin: "التحقق برقم الهاتف (OTP)",
    notVerified: "حساب قيد الانتظار لم يوثق",
    activeUser: "العضو النشط",
    changeStatus: "تعديل حالة الشكوى",
    upvoteBtn: "أنا أواجه هذه المشكلة أيضاً",
    commentsTitle: "حوار ونقاش",
    addComment: "كتابة تعليق ورأي",
    marketGoods: "غلال وسلع ومعدات",
    marketServices: "خِدْمَات زراعية ونقل",
    marketJobs: "عمالة وأجر يومي",
    addListing: "إضافة إعلان جديد",
    jobWage: "السعر أو الأجر",
    contact: "سجل هويتك للتواصل والمراسلة",
    anonymousPlaceholder: "مواطن مجهول",
    villageSelection: "القرية النشطة",
    resolvedSms: "تم إرسال إشعار SMS للمُبلِّغ",
    noComments: "لا توجد نقاشات دُونت بعد.",
    writeOpinion: "اكتب رأيك هنا...",
    notifFirst: "يرجى تسجيل الدخول برقم الهاتف أولاً لتتمكن من التعليق.",
    reportLoginRequired: "يجب إتمام التحقق من رقم الهاتف لتقديم شكاوى رسمية.",
    directForums: "مجالس نقاش القرية",
    villageGroups: "حوارات اللجان الأهلية بالقرية",
    emptyGroup: "لم يكتب أحد بعد في هذا القسم. بادر بالمشاركة واستفتح الخير!",
    anonymousMode: "وضع الكتمان (أخفِ اسمي)",
    typeGroupMessage: "اكتب رسالة للمجموعة الكريمة...",
    groupLoginRequired: "التحقق من رقم الهاتف مطلوب للمشاركة في غرف الحوار.",
    otpCredentials: "بوابة التسجيل الآمن للهاتف",
    sandboxHeader: "أدوات الفحص السريع (سيليت)",
    sandboxDesc: "بدل الأدوار لمعاينة صلاحيات رئيس القرية وتلقي إشعارات الـ SMS التجريبية:",
    villagerDesc: "يستطيع تقديم بلاغات وتأييدها، ونشر عروض للبيع في السوق الأهلية",
    pradhanDesc: "يملك سلطة تحديث حالة شكاوى المواطنين وبث تنبيهات الطوارئ العاجلة",
    newAccount: "تسجيل حساب جديد بالقرية والتحقق",
    nameLabel: "الاسم الكريم ثلاثيا",
    phoneLabel: "رقم الجوال النشط (10 أرقام)",
    roleLabel: "الدور المطلوب للتسجيل",
    residentRole: "مواطن من أهل القرية",
    pradhanRole: "رئيس المجلس القروي / المختار",
    otpSend: "طلب رمز التحقق OTP",
    otpCodeMsg: "أرسل الرمز السري! لغرض الفحص أدخل: 1234",
    verifyCode: "تأكيد والتحقق من الرمز",
    cancel: "إلغاء الأمر",
    activeCredentials: "تفاصيل الدخول الحالية",
    actionReport: "لجنة معالجة البلاغات وإصلاحها",
    statusSelect: "مرحلة المعالجة الحالية",
    notesLabel: "ملحوظات لجنة الإصلاح الرسمية",
    notesPlaceholder: "مثال: تم إرسال الفني واستبدال المحول الكهربائي المعطل وعادت الكهرباء.",
    webhookDesc: " فور تحويل البلاغ إلى 'تم الحل'، سيرسل النظام رسالة نصية وواتساب تفاعلية للمطلق تفيد بالإصلاح المنجز.",
    saveChanges: "حفظ وتحديث ملف الإصلاح",
    allCategories: "جميع الفئات",
    contactSms: "اتصال أو إرسال SMS",
    loginToContact: "سجل الدخول لعرض الرقم",
    farmersGroup: "🌾 منبر المزارعين",
    youthGroup: "🤝 منتدى الشباب الأهلي",
    womenGroup: "👩 جمعيات تمكين المرأة",
    generalGroup: "💬 قضايا عامة وشاملة"
  },
  zh: {
    appName: "智慧乡里 GramSwaraj",
    appSubName: "乡村治理与农产品市集",
    alertFeed: "紧急预警公告",
    homeTab: "民生动态",
    reportTab: "诉求上报",
    marketTab: "农贸集市",
    groupsTab: "村民议事厅",
    profileTab: "村民档案",
    anonymous: "匿名提交",
    postAnonymously: "允许匿名发布",
    anonymousHint: "选中后您的尊姓大名将在公共留言板上向普通村民完全遮蔽。",
    phoneLogin: "手机验证码安全登录",
    notVerified: "未认证审核账号",
    activeUser: "当前登录账户",
    changeStatus: "工单状态流转",
    upvoteBtn: "我也遇到了这个困难",
    commentsTitle: "互助讨论",
    addComment: "发表我的看法",
    marketGoods: "农资商品 / 粮食",
    marketServices: "农机租赁及服务",
    marketJobs: "零工招聘与求职",
    addListing: "发布新供求信息",
    jobWage: "期望价格 / 日薪",
    contact: "登录后查看联系方式",
    anonymousPlaceholder: "热心匿名村民",
    villageSelection: "当前所属村社",
    resolvedSms: "已向诉求人发送办结短信",
    noComments: "暂无任何村民评论回复。",
    writeOpinion: "请文明发表您的留言评论...",
    notifFirst: "请前往个人档案页面通过手机号和验证码登录后再评论。",
    reportLoginRequired: "为了工单的后续真实留痕，请先进行手机验证码登录。",
    directForums: "村政专题议事榻",
    villageGroups: "村民小组在线座谈网",
    emptyGroup: "此议事大厅暂时还没有消息，欢迎您写下第一条留言！",
    anonymousMode: "匿名身份发布",
    typeGroupMessage: "请输入要向议事厅发送的群聊消息...",
    groupLoginRequired: "根据互联网信息规范，参与互动需先完成身份认证。",
    otpCredentials: "实名和验证通道",
    sandboxHeader: "测试切换沙箱",
    sandboxDesc: "您可以通过一键切换不同测试身份来体验首席村民和普通农户的功能差异：",
    villagerDesc: "可以进行民生诉求上报、为他人诉求点赞，并可在市场上发布农副产品求购",
    pradhanDesc: "可以一键流转处理诉求，并可向全乡村民广播推送紧急公共安全预警",
    newAccount: "村民快速注册登录（免实卡验证）",
    nameLabel: "村民真实姓名",
    phoneLabel: "十位印度本地手机号",
    roleLabel: "欲注册身份角色",
    residentRole: "普通村民居民 (Resident)",
    pradhanRole: "村委会主任 / 村长 (Gram Pradhan)",
    otpSend: "获取手机登录码",
    otpCodeMsg: "演示登录码已生成，请输入演示验证码: 1234",
    verifyCode: "核验输入并建立档案",
    cancel: "放弃并退出",
    activeCredentials: "当前已认证权限秘钥",
    actionReport: "民生问题办结处理单",
    statusSelect: "诉求处理最新阶段",
    notesLabel: "村委会问题处理进展记录",
    notesPlaceholder: "例如：漏水主管道阀门已完成整体更换，生活用水已全部恢复供应。",
    webhookDesc: "一旦您选中“Resolved (办结)”，系统将自动调度 Zapier/Make 服务，向诉求人下发短信更新通知。",
    saveChanges: "确认修改工单状态",
    allCategories: "全部供求分类",
    contactSms: "联系发布商",
    loginToContact: "登录系统才可查看",
    farmersGroup: "🌾 农业互助组",
    youthGroup: "🤝 青年联谊会",
    womenGroup: "👩 妇女互助工作坊",
    generalGroup: "💬 村民百姓杂谈"
  }
};
